### ISSUE TITLE
Lag and visual issues in the composer window

### ISSUE THREAD

**Issue by TGRush** [TheBLVD/mammoth#101]
**Describe the bug**
I have noticed that on my iPad Air 2, there is a lot of lag in the composer window. When replying to someone, there is also some visual issues which could be related to the lag.

**To Reproduce**
1. Start composing a post or reply to someone else. 
2. Try typing something
3. Your input is going to be displayed very slowly, with a ~350-500ms delay. (If you‘re replying, you‘ll also see the window‘s content, such as your profile picture and the text jump around)

**Expected behavior**
I expect the text to appear very shortly after I write to keep the writing experience fluid. I also expect that the contents of the composer window don‘t jump around when replying.

**Device (please complete the following information):**
 - Device: iPad Air 2
 - OS: iOS 15.7.1
 - Version 1.6 Build 175

**Comment by NathanRLiu** [comment]
Interesting find. We'll look into the slowness.

**Comment by bvon** [comment]
Fixed in version 2 (unable to repro)
