### ISSUE TITLE
Home button in tab bar to scroll to top and back stops working

### ISSUE THREAD

**Issue by gwcali** [TheBLVD/mammoth#103]
**Describe the bug**
After switching the feed, the home button in the tab bar stops working and no longer scrolls to the top and back to where you were in the feed. Force-closing the app fixes it until you switch the feed again.

**To Reproduce**
1. Change the feed type
2. Tap on Home button in tab bar
3. Gets haptic feedback but nothing happens on screen.

**Expected behavior**
Home button should navigate to the top of the feed and back to the previous position

**Screenshots**
attached.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.5
 - Version: 1.7 Build 186

![Screenshot 2023-05-24 at 11 53 56 AM](https://github.com/TheBLVD/mammoth/assets/7017846/a7a6a1dc-5fc9-4dc6-b97f-9a925bc30673)

**Comment by bdecrem** [comment]
Thanks for reporting this here. I see the issue you describe, in 1.7. We're going to redo this part of our code & user experience in the coming weeks --pls bear with us, but this is a high priority issue

**Comment by bvon** [comment]
Fixed in version 2 :)
