### ISSUE TITLE
Mammoth Keyboard Issue in Posting Non-English Tooots

### ISSUE THREAD

**Issue by CDN18** [TheBLVD/mammoth#104]
**Describe the bug**
When I type the first character using Chinese/Japanese, the keyboard automatically inserts the character I typed, causing the first word of my post to be unable to appear normally.

**To Reproduce**
1. Tap on the compose button
2. Switch to the Chinese/Japanese Keyboard
3. Try to type a word. The first character of the word will be automatically inserted into the post instead of being combined with other characters to form the word.

**Expected behavior**
Non-English keyboards can integrate with mammoth normally.

**Screenshots**
![image](https://github.com/TheBLVD/mammoth/assets/46210502/4bc6b5e7-a732-43ff-ada0-8c56663d7b95)

**Smartphone (please complete the following information):**
 - Device: iPhone SE3
 - OS: iOS 16.5
 - Version [e.g. 22]: 1.7 Build 186

**Additional context**

**Comment by NathanRLiu** [comment]
Hey there! Thanks for the report. Currently on our list of things to fix!

**Comment by CDN18** [comment]
It's been fixed in v2.0 beta. Thanks very much for the effort!
