### ISSUE TITLE
New version of the app loses feed position when closed or re-loads.

### ISSUE THREAD

**Issue by dchansen42** [TheBLVD/mammoth#105]
**Describe the bug**
The most recent iOS version, the version prior, are not retaining the (following) feed location whenever the client is opened or has to re-load. It is sending you towards the top of the (following) feed list though it does not seem to be sending me to the most recent post when it does this.

**To Reproduce**
1. Note the last post you read.
2. Close the app and, if necessary in your case, wait a bit for your feed to populate with enough new posts.
3.  Open the app.
4. You should now see that your position in the following feed is not where you left off and is considerably more recent than it should be. In my case, I have been several days behind for at least a week and it was easy to see that whenever I opened the app, my position was on a different post that would be few hours, or several minutes, old rather than being 2-3 days old which would have been where I left off.  

**Expected behavior**
The app should remember the following feed position where the reader left off.

**Screenshots**
Not applicable/necessary. I could make some but I do not believe it would be helpful in this case.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.5
 - Version [e.g. 22]: 1.8.1 (Build 197)

**Additional context**
I initially noticed this with the previous version. Going back to Mammoth after the previous version was installed, the post position changed. I then noticed that any time the app had to either re-load or was closed and opened again that the post position would not be where I had left off. This behaviour continued with the version that followed it and is now the current version. A couple of times the app re-loaded on me and the behaviour was the same as if it had been closed and then re-launched.

And I do not know if this is related or if I should file a different ticket for it but the "message count" indicator, that floats in the upper right, either disappears or it just displays "20" and does not change.

**Comment by NathanRLiu** [comment]
Thanks for letting us know!

**Comment by bvon** [comment]
Issue resolved (MAM-1586)
