### ISSUE TITLE
Messages feed spinner spins forever

### ISSUE THREAD

**Issue by vpzed** [TheBLVD/mammoth#109]
**Describe the bug**
Messages pane doesn't load messages and on refresh the spinner stays spinning forever. 

**To Reproduce**
Open app, select envelope icon to open Messages pane. Pull down to refresh.

**Expected behavior**
Messages load into the Messages pane, or an indication appears that there are no messages.

**Screenshots**
![IMG_0014](https://github.com/TheBLVD/mammoth/assets/30138020/f3911a08-9e04-4b80-ab96-0f21d16e5988)

**Smartphone (please complete the following information):**
 - Device: 5th generation iPad Pro 12.9
 - OS: iPadOS 16.5.1
 - Version [e.g. 22]: 1.9 build 213

**Additional context**
Checking on another client, I did not have have any messages at the time of the test, so the specific behavior desired was the spinner to stop and be replaced with a message that no messages were found.

**Comment by bdecrem** [comment]
I think this is the same issue as 108, have filed a ticket, will let you know when we think we've fixed this.

**Comment by bvon** [comment]
Issue resolved (MAM-2081)
