### ISSUE TITLE
Large gaps in feed with no mechanism to load missing

### ISSUE THREAD

**Issue by vpzed** [TheBLVD/mammoth#110]
**Describe the bug**
Home feed shows large time gap but there is no mechanism provided to load missing posts.

**To Reproduce**
Open app, select house icon to open Following pane. Scroll messages.

**Expected behavior**
A mechanism is provided to load missing posts.

**Screenshots**
![IMG_0012](https://github.com/TheBLVD/mammoth/assets/30138020/3320f78f-d5a3-4261-8381-52dccda43fac)

**Smartphone (please complete the following information):**
 - Device: 5th generation iPad Pro 12.9
 - OS: iPadOS 16.5.1
 - Version [e.g. 22]: 1.9 build 213

**Comment by bdecrem** [comment]
this one too should be addressed in 1.10 next week: in 1.10 we are doing a full rewrite of our timeline (so that would fix a big crasher or two, incl the one you filed + should resolve issues to do with timeline gaps, among others)

**Comment by bvon** [comment]
Issue has been addressed in version 2 (MAM-1377)
