### ISSUE TITLE
App crashes frequently when attempting normal actions like Reply

### ISSUE THREAD

**Issue by vpzed** [TheBLVD/mammoth#111]
**Describe the bug**
Attempting to perform actions in Home pane other than viewing feed causes the app to crash/exit. It is intermittent and not repeatable.

**To Reproduce**
Open app, select house icon to open Following pane, click on Reply, Boost, Favorite, or action under the "..." menu such as Share Post.

**Expected behavior**
The app does not instantly exit and instead performs the requested action.

**Screenshots**
The app crashes too quickly to get a screenshot

**Smartphone (please complete the following information):**
 - Device: 5th generation iPad Pro 12.9
 - OS: iPadOS 16.5.1
 - Version [e.g. 22]: 1.9 build 213

**Additional context**
I have not yet determined a way to make this repeatable.

**Comment by bdecrem** [comment]
hey @vpzed these reports are awesome, though of course such a bummer to all see land and feeling bad you're having such a poor experience!!  thank you for filing these.

this one I think we're going to fix in 1.10, about a week from today.

**Comment by vpzed** [comment]
Something I forgot to mention is I use Mammoth on my iPhone and I see the crashing issue there, but not nearly as often. However some of the other issues I just reported don't occur there, like the ever-spinning Messages.  So not sure how much of a difference the iPad versus iPhone code makes, or if it's because my iPad is M1. I've never developed for iOS so unfortunately I can't be of much help.

**Comment by bvon** [comment]
Issue appears to be addressed in version 2
