### ISSUE TITLE
Mini games access and scores

### ISSUE THREAD

**Issue by Velkas** [TheBLVD/mammoth#112]
It would be fun if the scores from the mini games in the settings menu would be saved to the statistics page! It would also be nice if there could be an option to enable access to them from the main app pages instead of hidden behind several taps.

**Describe the solution you'd like**
When completing a game, score and playtime could be recorded into a new section in the statistics menu. For numbers specifically, a high score label could be created and displayed while playing a new game.

An option could be added to the appearance menu to enable some kind of action to access either game from the home page. Such as triple tap the home icon to bring up mini game selector for example. 

**Additional context**
I realize this isn't the purpose of the app and it's just a nice little bonus but I have genuinely been playing the numbers mini game a lot when taking a break from scrolling feeds. Just got annoyed by how many clicks it takes to play and not seeing my high score to beat.

**Comment by NathanRLiu** [comment]
Unfortunately we are planning on getting rid of the minigames :(
