### ISSUE TITLE
Cannot using custom emojis

### ISSUE THREAD

**Issue by su010423** [TheBLVD/mammoth#113]
https://github.com/TheBLVD/mammoth/assets/10346718/af1f042c-9c8f-4acb-aeb5-7a1fd93e5f0d

When I select a custom emoji, it is not select normally.

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11 3rd Gen
 - OS: iPadOS 15.6.1
 - Version [e.g. 22]: 1.9 Build 213

**Comment by NathanRLiu** [comment]
Interesting. We will start tracking this issue. Thanks for letting us know!

**Comment by NathanRLiu** [comment]
Actually, this should be fixed now. Can you confirm?
