### ISSUE TITLE
Refreshing feed sound pauses music

### ISSUE THREAD

**Issue by henhouse** [TheBLVD/mammoth#115]
**Describe the bug**
When listening to music (in my case Spotify) on iOS and refreshing a feed on Mammoth, the refresh sound that plays causes music playback to be paused.

**To Reproduce**
1. Have music playing via Apple Music, Spotify, etc.
2. Open Mammoth
3. Scroll down from top to refresh feed
4. Notice your music pause as the refresh sound effect plays

**Expected behavior**
I presume the sound effect should play without pausing music.

**Screenshots**
Video instead:
https://github.com/TheBLVD/mammoth/assets/30731/80888ad1-7c07-4465-b00b-5d0474612a1c

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 16.6
 - Version: 237

**Comment by NathanRLiu** [comment]
Hey! This should be fixed in the latest build.
