### ISSUE TITLE
Non-DM notifications are sent as urgent notifications

### ISSUE THREAD

**Issue by marcusirgens** [TheBLVD/mammoth#118]
**Describe the bug**
I receive notifications immediately when people like my posts, but I have configured Mammoths notifications to only be delivered in summarized format.

**To Reproduce**
1. Go to the iPhone notification settings
2. Deliver notifications by schedule for Mammoth
3. Post sometime if and wait for interactions
4. Receive immoderate notifications because “like” notifications are considered to be “direct messages”.

**Expected behavior**
I expect only direct messages to deliver instant notifications when the setting is enabled.

**Screenshots**
![IMG_7003](https://github.com/TheBLVD/mammoth/assets/8811904/fca9e96c-6a2e-412d-9837-5ba611f3a42d)
![IMG_7004](https://github.com/TheBLVD/mammoth/assets/8811904/2daba015-976c-4cd4-be50-1f6b72c3b496)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.5.1 (c)
 - Version 2.0, build 236

**Additional context**
This behavior reduces my ability to limit unnecessary notifications, and feels like a violation of trust, even though I assume it’s a programming error.

**Comment by NathanRLiu** [comment]
Nice find. Thanks for bringing this to our attention! I will write up a ticket for this.

**Comment by bvon** [comment]
Tested this in Build 359. Turned on Scheduled Delivery for 1am, repeated the steps using two devices, and couldn't reproduce. Looks like this has been fixed.
