### ISSUE TITLE
Missing posts issue.

### ISSUE THREAD

**Issue by dchansen42** [TheBLVD/mammoth#121]
**Describe the bug**
I do not follow many active posters and only two hashtags and it has been noticeable that the app seems to drop a number of posts from my feed (Following tab). For a while I thought it was just me and then I confirmed this by opening another app and while attempting to scroll it up to where I left off in Mammoth I saw a great many posts in my feed that I had not seen in Mammoth. 
 
I suppose there must be some inherent issue with timing, amongst other issues, of some instances being more responsive than others but I also assume it should be a surmountable issue.

**To Reproduce**

**Expected behavior**
I would think that the app would be able to display all of the followed posts in a reasonable, non-chaotic manner. Even if it means that some late arrivals (If this is part of the issue.) just get displayed in arrival order.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro
 - OS: iOS 16.6 (20G75)
 - Version [e.g. 22]: v1.10.1, build 239

**Additional context**

**Comment by NathanRLiu** [comment]
Thanks for letting us know! Were the missing posts from followed hashtags or followed users?

**Comment by xhaythemx** [comment]
Salle issue for me and it’s for both hashtags and users

**Comment by dchansen42** [comment]
It is from both. 

As mentioned previously, I had suspected this was going on for awhile but it was confirmed recently after I started to follow the NPR account. I was getting the same story repeated in my feed, but not re-posts, sometimes minutes apart and sometimes hours apart so after a bit I went to their profile to see if they were actually posting the same stories multiple times as new or if there was some glitch. I confirmed that not only is it some regrettable action on their part but mixed in between were a number of posts that I had not received. I then opened another Mastodon client and verified that it showed a lot of posts in my feed there that I had not read before and from both other accounts as well as followed hashtags.

**Comment by bvon** [comment]
I believe this issue has been sorted out. Can we confirm @jtomchak @rileyhCode ?

**Comment by rileyhCode** [comment]
> I believe this issue has been sorted out. Can we confirm @jtomchak @rileyhCode ?

Yes; pls recheck with the most recent build; should be all good now.

**Comment by bvon** [comment]
> > I believe this issue has been sorted out. Can we confirm @jtomchak @rileyhCode ?
> 
> Yes; pls recheck with the most recent build; should be all good now.

LGTM. Closing
