### ISSUE TITLE
Extra letter in posts

### ISSUE THREAD

**Issue by Qusea** [TheBLVD/mammoth#124]
**Describe the bug**
Every post in my timeline has the letter 'p' added to the beginning of the post.

**To Reproduce**
1. Open app

**Expected behavior**
Posts show up as written by author.

**Screenshots**
![image](https://github.com/TheBLVD/mammoth/assets/6491176/bd60605f-dd1d-46d2-9bcd-8d7898a2444c)

![image](https://github.com/TheBLVD/mammoth/assets/6491176/5c581f74-c069-4673-b984-509c3af3d4ff)

![image](https://github.com/TheBLVD/mammoth/assets/6491176/eab2ce18-9e94-4826-aab8-4d4d00cf3273)

![image](https://github.com/TheBLVD/mammoth/assets/6491176/583d501d-0d58-4fe5-b39b-a38151af82a2)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 16.6
 - Version: 1.10.1
 - Build: 239

**Additional context**

**Comment by NathanRLiu** [comment]
Hey! I tried to reproduce this bug but I'm having a hard time doing so. Is this still happening?

**Comment by Qusea** [comment]
I think I isolated the issue. I had the 'remove all emoji' option turned on. When I turned it off the extra letter disappeared, and it reappeared when I turned it on again.

**Comment by NathanRLiu** [comment]
> I think I isolated the issue. I had the 'remove all emoji' option turned on. When I turned it off the extra letter disappeared, and it reappeared when I turned it on again.

Great catch!

**Comment by NathanRLiu** [comment]
I'm able to reproduce it this way too - thanks! We're getting rid of this setting but good to know that was the root cause.

**Comment by Qusea** [comment]
Can I ask why you’re removing the option?
I personally like having it because I hate emoji.

Qusea Saif

**Comment by NathanRLiu** [comment]
> Can I ask why you’re removing the option? I personally like having it because I hate emoji. Qusea Saif
> […](#)
> On Aug 23, 2023 at 2:36 AM +0300, NathanRLiu ***@***.***>, wrote: I'm able to reproduce it this way too - thanks! We're getting rid of this setting but good to know that was the root cause. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

We're trying to cut back on having too many settings and opting for a leaner but more streamlined approach. It can be a lot to keep track of, which ended up being the case here where it led to this tricky bug. Too many settings means that there's a lot of variability to account for when trying to track down bugs (and push features), which makes development take longer.

**Comment by Qusea** [comment]
I understand. Thank you for letting me know.

Qusea Saif
