### ISSUE TITLE
Sharing link from other services

### ISSUE THREAD

**Issue by elegansen** [TheBLVD/mammoth#125]
When I go to, say, a YouTube video and tap the share button, I can choose to share video link to Mammoth. But when I do this, YT just switches to Mammoth... and then nothing else. It doesn't compose a new toot with the link inside. So that functionality would be greatly appreciated.

Also: it would also be great if you could choose which Mastodon account you would like to share the link to (if you have several accounts active in Mammoth) when you tap Share to Mammoth on Youtube. The Toot! app does this very nicely.

Thanks for building (and improving) the best Mastodon app out there!

**Comment by NathanRLiu** [comment]
Thanks for letting us know! This issue is currently on our list of things to fix.

**Comment by bvon** [comment]
Fixed in Mammoth 2!
