### ISSUE TITLE
Option to view videos with sound with ringer switch off

### ISSUE THREAD

**Issue by danielton1** [TheBLVD/mammoth#126]
Hi there, I'm loving this app for the most part so far. However, I almost always keep my phone's ringer off, and most social media apps allow me to watch videos with sound without having to turn the ringer switch on, except this one. At first I thought Mammoth didn't support sound at all, even though the on-screen controls showed the sound was turned on, but I later tried it with the ringer switch turned on and sure enough, I got sound.

I'd love an option to turn the sound on even if the ringer is off! Otherwise, I love the design of this app and it makes Mastodon feel more familiar.

**Comment by NathanRLiu** [comment]
Hey! This is already resolved in the latest beta build - it should reach the app store build in the next release. Thanks for the feedback!

**Comment by danielton1** [comment]
Thank you!
