### ISSUE TITLE
Theme chooser not reflecting selected option

### ISSUE THREAD

**Issue by drewfranz** [TheBLVD/mammoth#129]
**Describe the bug**
When selecting a Theme option (i.e. “Dark Mode”) the check mark of the newly-selected option is not accurate. For example, by default the Theme value is “System”. If you select “Dark” then re-open the select field the check mark is still on System. 

**To Reproduce**
1. Go to “Settings”
2. Tap on “Text and Tints”
3. Scroll down to “Theme”
4. Tap on “Theme”
5. Tap on “Light” or “Dark”
6. Tap on “Theme” again
7. See that even though the theme UI has changed, the select check mark is still on “System”

**Expected behavior**
After selecting an option in the “Theme” dropdown, the selected option should have a check mark next to it. 

**Screenshots**

https://github.com/TheBLVD/mammoth/assets/700114/7e4ca9bd-fafb-4c8e-bdb3-d28008d5cd87

**Smartphone (please complete the following information):**
 - Device: iPhone13 Pro Max
 - OS: iOS 17.0 Developer Beta 7 (21A5312c)
 - Version: 2.0 Build 261

**Comment by NathanRLiu** [comment]
Good find! I'll put this on our list of bugs to fix :)

**Comment by NathanRLiu** [comment]
The changes have been merged and you should see the fix in next week's TestFlight build :)

**Comment by bvon** [comment]
Fixed in Mammoth 2!
