### ISSUE TITLE
Setting label font size changing

### ISSUE THREAD

**Issue by drewfranz** [TheBLVD/mammoth#130]
**Describe the bug**
When changing the selected setting option for “Theme” (ie Dark Mode) the label for “Font Style” is changing font size. It seems to toggle between two slightly different sizes when selecting the “Theme” value. 

**To Reproduce**
1. Go to “Settings”
2. Tap on “Text and Tints”
3. Scroll down to where both “Theme” AND “Font Style” are visible 
4. Tap on “Font Style”
5. Tap on a different Font Style option
6. Without leaving this View, tap on “Theme”
7. Tap on the currently active Theme option (ie, don’t chose new theme value)
8. See error. You should see that when the “Theme” field dropdown closes the “Font Style” font size changes slightly. 

**Expected behavior**
When selecting a setting option the label formatting of any other field should not be changed. 

**Screenshots**

https://github.com/TheBLVD/mammoth/assets/700114/a557f7eb-0ef2-4786-9e1d-b7ae5de25fca

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 17.0 Developer Beta 7 (21A5312c)
 - Version: 2.0 Build 261

**Additional context**
this one is a tricky, one to re-create, so be sure to follow the steps above exactly

**Comment by NathanRLiu** [comment]
Interesting. I'll take a look at this

**Comment by bvon** [comment]
This issue has been resolved in Mammoth 2
