### ISSUE TITLE
Toots often render 1-3 characters per line

### ISSUE THREAD

**Issue by danielton1** [TheBLVD/mammoth#131]
**Describe the bug**
I often get toots that only render 1-3 characters per line in my feed. They normally look fine once I open the toot.

**To Reproduce**
Scroll through feed, and a few toots will look like this

**Expected behavior**
Toots should appear the same way they do in the detail view

**Screenshots**
![IMG_2608](https://github.com/TheBLVD/mammoth/assets/143075798/ab9876c8-0b12-4b65-a357-3a40988b4d1b)
![IMG_2609](https://github.com/TheBLVD/mammoth/assets/143075798/5e389cf6-ed4a-4fff-b8f3-1d970c462d3b)
Link to the toot in the screenshots: https://mstdn.ca/@karinnelson/110976241994339025

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.6
 - Version: 1.10.2 Build 252

**Comment by NathanRLiu** [comment]
Thanks for filing. We will look into this.

**Comment by NathanRLiu** [comment]
I've seen this issue before, but am having a hard time reproducing it. Do you have any insights that you think might help?

**Comment by poopsicles** [comment]
It often happens when I'm reopening the app, like from sleep, after a while..then I usually just force-quit and open it up again

**Comment by derspyy** [comment]
haven't seen this in 2.0. can anyone reproduce?

**Comment by derspyy** [comment]
haven't seen this repro'd in 2.0, so i'll be closing
