### ISSUE TITLE
Not possible to reply to posts in beta 2

### ISSUE THREAD

**Issue by FabrizioMusacchio** [TheBLVD/mammoth#133]
Since build 261, replies to posts are not sent. You can indeed press the reply button and write your reply text. However, after clicking on the send button, the reply is not send and the entire text is gone/lost.

**Comment by NathanRLiu** [comment]
Hi Fabrizio, are you still seeing this?

**Comment by FabrizioMusacchio** [comment]
It's solved by the yesterday's update to build 269 👍 Thanks 🙏

**Comment by jobukkit** [comment]
I have experienced this issue on the latest App Store version as well (1.10.2 build 252). You press send and the entire text you typed is just gone.
