### ISSUE TITLE
Changing avatar doesn't change it everywhere

### ISSUE THREAD

**Issue by tollfree** [TheBLVD/mammoth#143]
Hi,
Not a big deal, but
Changing avatar on the website doesn't lead to change across all the app.

1. Go to https://mastodon.social or wherever
2. Tap on Edit profile
3. Change your Profile picture
4. Open Mammoth app
5. The new avatar now appears on your Profile tab but remains unchanged in the low right corner, as well as in the New post window and Accounts settings.

Opposite, changing avatar inside the app cause changes across all the app, also in the web.

**Smartphone:**
 - Device: iPhone 12Pro
 - OS: iOS 16.6.1
 - Version: 1.10.2  252

**Comment by bvon** [comment]
Hey, so sorry for the belated response! So this issue has been fixed in Mammoth 2 which should be released relatively soon. Thanks for reporting!
