### ISSUE TITLE
Filter Details toggles won't stay on

### ISSUE THREAD

**Issue by monkeyroar** [TheBLVD/mammoth#148]
**Describe the bug**
When I try to create a filter to hide completely posts with specific keywords, Mammoth won't save my toggle states after I press back.

**To Reproduce**
1. Go to 'Settings -> Filters -> Filter Detail'
2. Tap any of the Extras toggles
3. Go back
4. Open filter details again
5. See that my preferences weren't saved

**Expected behavior**
Toggles are in the same state that I set them

**Screenshots**
![IMG_DAEE810A979E-1](https://github.com/TheBLVD/mammoth/assets/95053773/e0d51c65-7ee1-4716-93be-7f5ade8cdd0e)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 12 Pro]
 - OS: [e.g. iOS17.0.3]
 - Version [e.g. 252]: The build number can be found in Mammoth's Settings, way at the bottom.

**Comment by bvon** [comment]
Thank you! I've filed a report with the developers and it's on their ToDo list. Will report back on the status for you.
