### ISSUE TITLE
Mammoth Crashes When Share Sheet Is Selected From Following

### ISSUE THREAD

**Issue by justaname2** [TheBLVD/mammoth#149]
**Describe the bug**

**To Reproduce**
1. Go to Following
2. Tap on three horizontal dots icon
3. Select Share
4. Mammoth crashes

**Expected behavior**
I expect a share sheet

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9" (Fourth Generation)
 - OS: 16.6.1
 - Version [e.g. 22]: 252
 
**Additional context**

**Comment by bvon** [comment]
Thanks for letting us know! This seems to be fixed in build 307, so the next available beta should fix this for you. If not, please let us know.

**Comment by justaname2** [comment]
You're welcome.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
