### ISSUE TITLE
Suggestion: More powerful list management interface

### ISSUE THREAD

**Issue by maegul** [TheBLVD/mammoth#15]
Lists are powerful but get clunky quickly as all interfaces are relatively minimal. Mammoth is pretty slick, so I figure you might be interested in innovating here. 

Ideas:

* easily display all lists a user is in 
* Check box interface for managing a user’s membership in any/all lists
* Someway to treat the `{list: (users, …), list2: (users, …)}` data more natively like the dataset that it is. Maybe more like a spreadsheet somehow, so that the user can have a Birds Eye view of their lists and shuffle users around to keep it clean and consistent.

**Comment by ShihabM** [comment]
This is a great idea, thanks!
