### ISSUE TITLE
Sound on speakers not working in videos

### ISSUE THREAD

**Issue by Parsijn** [TheBLVD/mammoth#153]
**Describe the bug**
No sound on phone speakers when playing videos that are posted. The sound _does_ work when playing videos and external speakers/headphones are connected through mini-jack or bluetooth.

**To Reproduce**
1. Make sure no external audio devices are connected to the phone.
2. Open the Mammoth app. 
3. Find a post with a video that has sound and make sure sound is not muted.
4. See error.

**Expected behavior**
Sound should be played over the phone speakers when playing a video.

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2016)
 - OS: iOS 15.8
 - Version: 1.10.2 Build 252

**Additional context**
Reinstalling the app did not help. Sound _does_ work on other apps like the official Mastodon app.

**Comment by bvon** [comment]
Hey, thank you for reporting this issue! This issue has been addressed in the latest version of Mammoth (version 2.0) which should be released next week barring any significant changes.

**Comment by Parsijn** [comment]
Awesome! Looking forward to the new version of this great app :)
