### ISSUE TITLE
mismatched id's when fetching profiles.

### ISSUE THREAD

**Issue by derspyy** [TheBLVD/mammoth#156]
different instances use different profile id's. 

mammoth requests remote profiles using the local id and the request always fails, falling back to local:

![image](https://github.com/TheBLVD/mammoth/assets/65043391/0c2ab213-74cf-4109-82a9-be3ba8c9e454)
> comparison between the web interface request and mammoth.

for a proper fallback, mammoth should start by trying to fetch the remote id.

![image](https://github.com/TheBLVD/mammoth/assets/65043391/8eb46a35-16aa-4f6d-981c-f70bf1437136)
> graph of the proposed fallback logic for profiles.

**Comment by derspyy** [comment]
if i'm right assuming this is the function that handles the initial request, it would be cool if i could get confirmation over which user id it's using.

https://github.com/TheBLVD/mammoth/blob/0d7aec5bb7987cf59972ef21f88c3e7a3a837738/Mammoth/Screens/ProfileScreen/ProfileViewModel.swift#L274-L279

**Comment by derspyy** [comment]
looking at the code and the fact that `AccountService.lookup()` always fetches remotely, you can kinda do it in a way simpler way?

![image](https://github.com/TheBLVD/mammoth/assets/65043391/66fddb42-6629-4b46-af2b-a6e797a81e2c)

**Comment by derspyy** [comment]
the mismatched id can match a random account on the target instance and open another profile. this goes deeper.

**Comment by bvon** [comment]
This is definitely something we should look into, @jtomchak. There's a ticket for this (MAM-3514) for reference

**Comment by derspyy** [comment]
on 2.1, i can't tell if this is fixed or not.

as far as i know, the intended logic is to try to load the profile's posts remotely and fallback to local only when it fails.
it's currently only doing local requests.

![image](https://github.com/TheBLVD/mammoth/assets/65043391/aa2c9641-f194-4abc-9c77-395ed62b24e0)

is this intended?

**Comment by derspyy** [comment]
well... intended or not, haven't seen weird behaviour.
