### ISSUE TITLE
zero replies on non-mastodon posts.

### ISSUE THREAD

**Issue by derspyy** [TheBLVD/mammoth#157]
looking at the app requests, the following is happening:

1. mammoth first requests the post locally and gets the replies correctly.
![image](https://github.com/TheBLVD/mammoth/assets/65043391/531d7828-4060-461f-a1d9-cc4787fedbe6)

2. then requests the same post remotely and fails to get information.
![image](https://github.com/TheBLVD/mammoth/assets/65043391/a32edd65-4994-4ae6-8751-fe90c4cdd5f4)

3. doesn't parse the first response, even though it succeeded.

**Comment by derspyy** [comment]
i'm not sure if the intended design is...
1. fetching remotely and then falling back to local on error just like profiles.
2. fetching locally and then falling back to remote on error.
3. fetching both and adding up the replies.

**Comment by sjimwillis** [comment]
Came here to report similar bug. I posted a reply, hit send and got error “Could not load.” Reply doesn’t appear in my activity feed in Mammouth, nor does it appear in my activity feed when view feed through web so looks like it didn’t post at all. Not sure if it’s related, but replies that I post on the web are not showing up in my activity feed on Mammouth.

**Comment by derspyy** [comment]
so you're not receiving replies to your posts? that's interesting. i think the activity feed does something else entirely but if i find anything related i'll let you know.

**Comment by derspyy** [comment]
will probably look into it further but the first thing that drew my eyes was this tasty slice:

https://github.com/TheBLVD/mammoth/blob/0d7aec5bb7987cf59972ef21f88c3e7a3a837738/Mammoth/Services/Backend/StatusService.swift#L389-L423

are all of these identical? am i looking at the right code?

**Comment by derspyy** [comment]
can u give me the user you're replying to?

**Comment by derspyy** [comment]
this seems to be the part that's failing. if this fallback/retry worked, we wouldn't even need the threads workaround right before it.

https://github.com/TheBLVD/mammoth/blob/50de2a10f0431370150d8f60ca2e3226f1aee33f/Mammoth/Screens/DetailScreen/DetailViewModel.swift#L274-L282

**Comment by derspyy** [comment]
seems fixed as far as i could test!
