### ISSUE TITLE
Fediverse backend/API support

### ISSUE THREAD

**Issue by EwanCroft** [TheBLVD/mammoth#166]
**Is your feature request related to a problem? Please describe.**
As mentioned [here](https://github.com/TheBLVD/mammoth/issues/27), the Fediverse isn't just Mastodon. There needs to be better handling of other software.

**Describe the solution you'd like**
Mammoth should integrate alternative microblogging software, such as Misskey and its forks, as well as Akkoma/Pleroma.

**Describe alternatives you've considered**
[N/A]

**Additional context**
I am on [Iceshrimp](https://iceshrimp.dev), so I thought about asking the above. There aren't very many apps across both iOS and Android for alternative backends.

**Comment by derspyy** [comment]
iceshrimp should have mastodon api support. of course you'd be missing some features (notably reactions) but it should be supported.

**Comment by EwanCroft** [comment]
i know it does, but not fully, though. I can do most things, but some areas are glitchy.

I get that this is also client-side, but it is annoying how links aren't clickable.
