### ISSUE TITLE
Feature request: show when a toot comes from tag you follow

### ISSUE THREAD

**Issue by gferreroferri** [TheBLVD/mammoth#17]
Show some kind of indicator in the toot to show that it comes from a tag you follow, to be able to differentiate from the people you follow

**Comment by sdubinsky** [comment]
Hi!  You're not the only one to want that.  Unfortunately, the way Mastodon is built, we don't have access to that information: https://github.com/mastodon/mastodon/issues/19528.  We'll keep it in mind for the future though
