### ISSUE TITLE
Incorrect posts are showing up on people’s profile

### ISSUE THREAD

**Issue by jonniedie** [TheBLVD/mammoth#195]
### Describe the bug

When I click on certain profiles in the Mammoth app, I see posts from a random other user that isn’t the one I clicked. Often it’s a Russian propaganda reposter. In other apps or on the Mastodon desktop site, I don’t see this happening.

### To Reproduce

Go to @Gargron@mastodon.social ‘s page in the Mammoth app

### Expected behaviour

There should be posts that @Gargron@mastodon.social either posted or reposted. 

### Screenshots

Here is an example (first is in the Mammoth app, the next is in the Mastodon app):
![IMG_2377](https://github.com/TheBLVD/mammoth/assets/47193959/e0269cbf-a5a6-4206-9efb-d1394834d6b6)
![IMG_2376](https://github.com/TheBLVD/mammoth/assets/47193959/5c797691-4bf4-4f36-bc17-6fe303621e81)

### Device

iPhone 12 Mini

### OS

iOS 17.1.2

### Version

2.0.2

**Comment by derspyy** [comment]
this is a consequence of #156.

**Comment by bvon** [comment]
Thanks for reporting this! We currently have an open ticket for this for the team to review

**Comment by derspyy** [comment]
this seems fixed
