### ISSUE TITLE
Unread notification missing

### ISSUE THREAD

**Issue by frepke** [TheBLVD/mammoth#20]
After fetching, no “unread” notification visible in the right upper corner most of the time.

**Comment by Krit1960** [comment]
This is the case when your entirely on top of the timeline. When this is not the case the counter shows up

**Comment by frepke** [comment]
That's what I'm expecting, but it doesn't work that way. I opened the app for the first time today and started the screen capture immediately: https://user-images.githubusercontent.com/6153559/221517499-6bcca46b-21ce-49f5-b860-bb062e419b48.MOV

**Comment by ShihabM** [comment]
Thanks for this! We'll be resolving this soon.

**Comment by frepke** [comment]
Still not solved in v1.1 build 119

**Comment by frepke** [comment]
And not solved in v1.2 build 128

**Comment by frepke** [comment]
Still not solved in version 1.3 build 134

**Comment by frepke** [comment]
And again, in v1.4 build 145 not fixed 😞

**Comment by NathanRLiu** [comment]
Hey there! We thought we had this issue resolved but we've gotten numerous reports coming in that this is still an issue. Thank you so much for being patient with us and letting us know. The issue has since been reopened for further review, and we expect the issue to be fixed in the next sprint.

**Comment by frepke** [comment]
I'm going to stop reporting this with every new version.

**Comment by bvon** [comment]
I believe this issue has been addressed in Mammoth 2, which should be out later this fall. Thanks for reporting!
