### ISSUE TITLE
When somebody includes the text '@username' in a post but it's not a mention, the text is incorrectly made into a profile link

### ISSUE THREAD

**Issue by nickludlam** [TheBLVD/mammoth#227]
### Describe the bug

An example is the following post:
https://mastodon.gamedev.place/@VrKomarov/111626405139037828

The toot contains the text:

> Just for fun did some tests with beautiful cloud from @bunnylever in my path tracer.

The '@bunnylever' text is incorrectly converted into a profile link. The original post JSON has an empty `mentions` array.

### To Reproduce

1. Bookmark or use some other way to navigate to https://mastodon.gamedev.place/@VrKomarov/111626405139037828 in Mammoth
2. Click on the linked @bunnylever 
3. Observe the **User can't be found** error

### Expected behaviour

The username should not become a profile link

### Device

iPhone 15

### OS

iOS 17.2.1

### Version

2.1 build 359

**Comment by bvon** [comment]
Thanks for reporting! Filing a ticket on this now.

**Comment by bvon** [comment]
Hello again! Is this still an issue for you in the latest build?

**Comment by nickludlam** [comment]
Sorry for the delay. I've checked again, and this now working correctly.
