### ISSUE TITLE
Badly generated website preview

### ISSUE THREAD

**Issue by mikix** [TheBLVD/mammoth#228]
### Describe the bug

I don’t know whose fault this is, I’m just reporting the final symptom. I posted a link to a website from my moth.social account, and the resulting in-app link preview seems buggy.

Here is that preview in app:
<img width="414" alt="image" src="https://github.com/TheBLVD/mammoth/assets/1196901/66e5068e-fb1f-4c45-820f-c45cde828c8a">

Here is that preview on web:
<img width="359" alt="image" src="https://github.com/TheBLVD/mammoth/assets/1196901/faffceed-c722-415f-ae9e-a4ad96a317a2">

Here is the site: https://flathub.org/apps/org.gnome.DejaDup

Here is my post: https://moth.social/@mikix/111627131754792098

### To Reproduce

1. View my linked post above in app

### Expected behaviour

A better aligned icon 

### Device

iPhone 11

### OS

17.2.1

### Version

Build 359

**Comment by mikix** [comment]
New behavior: now the preview looks like below, which is maybe better, but still not ideal

<img width="414" alt="image" src="https://github.com/TheBLVD/mammoth/assets/1196901/fce3fe0f-9dde-4221-b3f3-fe1a0653dc80">

**Comment by nickludlam** [comment]
If you check the formatting of the `og:image` on https://www.opengraph.xyz/url/https%3A%2F%2Fflathub.org%2Fapps%2Forg.gnome.DejaDup you can see the same issue happens with other sites, so it's not strictly Mammoth's fault here, especially after #213 fixed the issue with an ImageView which wasn't spanning the screen width correctly.

According to [Facebook's OpenGraph documentation](https://developers.facebook.com/docs/sharing/webmasters/images/):
> Try to keep your images as close to 1.91:1 aspect ratio as possible to display the full image in Feed without any cropping.

So it's then down to the layout of the preview card as to whether the image is framed without cropping.  An image with text on the right looks ok, and an image with text underneath looks poor.
