### ISSUE TITLE
Feature request: Longpress on follow initiates pop-up with option to use secondary account

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#23]
As title, So longpressing on "Follow" on an account gives sub-menu where one can choose which account should do the follow. Same way longpressing Reply, Like or Boost displays option to do that without the need to switch account beforehand.

**Comment by bdecrem** [comment]
Omg I literally had that same thought a minute ago!

**Comment by ShihabM** [comment]
This is a great idea, thanks!
