### ISSUE TITLE
Can’t see the replies sent by others to some users

### ISSUE THREAD

**Issue by mastro35** [TheBLVD/mammoth#230]
### Describe the bug

I can’t see replies to some profiles. When I open a toot of these profile I get a “can’t load more” error.

The attached screenshot is about an Adam Mosseri toot but this happen even with users that are on regular instances of Mastodon, not just for threads.net accounts.

### To Reproduce

Just open a toot written by Adam Mosseri or @chiaraepoi@redsnake.io. Apparently it happens on all threads.net and redsnake.io profiles. 

I don’t have any problems with other clients (eg ice cube)

### Expected behaviour

Opening a toot you see the replies

### Screenshots

![IMG_0094](https://github.com/TheBLVD/mammoth/assets/399990/17b61a2a-cf73-4c39-9fd6-c7c902ceee5a)

### Device

iPhone 15 pro

### OS

IOS 17.2.1

### Version

2.1

**Comment by bvon** [comment]
Just checking in to see if this is still an issue for you with the current build?

**Comment by mastro35** [comment]
No, it seems to work fine with the latest version. 
thanks
