### ISSUE TITLE
Images are lower resolution than it should be

### ISSUE THREAD

**Issue by bravecrayon** [TheBLVD/mammoth#231]
### Describe the bug

It appears that images are downloaded, displayed, and saved in a lower resolution than it should be when compared to Ivory. 

### To Reproduce

1. Tap on image preview
3. Long-tap to download image
4. Repeat in Ivory
5. Compare photos

### Expected behaviour

Expected to load, display, and save image in full available resolution.

### Screenshots

Ivory 1440x1080: ![2776C2C0-2A9B-4B83-87FC-4023D912B137](https://github.com/TheBLVD/mammoth/assets/43159603/498aa096-a2e8-471d-9201-3bd42edd153d)

Mammoth 554x416: 
![IMG_8377](https://github.com/TheBLVD/mammoth/assets/43159603/e95cd0c2-8058-49b7-97e1-f0fca65dd560)

### Device

iPhone 15 Pro Max

### OS

iOS 17.2.1

### Version

v2.2 Build 362

### Additional context

https://pixelfed.de/p/azipp/644523146196797781

**Comment by bvon** [comment]
Thanks for the report! Got an open ticket for this for the engineers.

**Comment by bvon** [comment]
Update: hi-res images has been added to the internal build and we're testing it. Should be available in the next TestFlight build most likely!

**Comment by seanthingee** [comment]
Awesome👍

**Comment by bravecrayon** [comment]
Awesome!👍

**Comment by bvon** [comment]
Now available in the App Store version!
