### ISSUE TITLE
Feature request: Toggle to switch and/or disable preview of profile picture in notification

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#24]
Mammoth displays the profile picture of where the notification originates from as icon in the notification but a smaller icon is also shown where the currently selected app icon is displayed. 

A settings toggle to switch places with these two and a toggle to disable preview of user profile picture altogether. 

Example, (my current app icon is set to the orange)
 ![image](https://user-images.githubusercontent.com/120338442/221375847-9651c118-8324-4f66-b6df-1691b530227c.jpeg)

**Comment by ShihabM** [comment]
Thanks for the suggestion!
