### ISSUE TITLE
iOS App Freezes When Muting and Un-Muting Accounts

### ISSUE THREAD

**Issue by ThomsenDrake** [TheBLVD/mammoth#240]
### Describe the bug

When attempting to mute an account forever on iOS the app freezes completely until the app is terminated and re-opened.

### To Reproduce

When muting:
1. On the iOS app open a profile
2. Click the gear on the top right of the profile 
3. Select the mute dropdown
4. Select “mute forever”

When un-muting:
1. On the iOS app open a profile
2. Click the gear on the top right of the profile
3. Select “unmute”

### Expected behaviour

Confirmation that account was muted and continue on to regular app usage

### Screenshots

![IMG_0251](https://github.com/TheBLVD/mammoth/assets/120344051/4d214cce-b00c-491a-837c-0ad746d2e574)

### Device

iPhone 15 Pro Max

### OS

iOS 17.2.1

### Version

2.2 Build 362

**Comment by bvon** [comment]
Nice find! Thanks for reporting. I'll ticket this and pass it on to the engineers.

**Comment by ThomsenDrake** [comment]
Thank you! Also, just to add: when the mute/unmute button is pressed the action is still performed. When I terminate and re-open the app and check the profile I was muting they do show as muted.

**Comment by bvon** [comment]
This should be fixed in the newest Beta, and in the App Store version!
