### ISSUE TITLE
Unable to load remote posts from users not on Mastodon

### ISSUE THREAD

**Issue by ThatOneCalculator** [TheBLVD/mammoth#26]
**Describe the bug**
Posts from remote users on other software like Calckey, Akkoma, Friendica, etc simply don't load. https://mastodon.social/@atomicpoet/109929233160378968

**To Reproduce**
1. Load remote profile

**Expected behavior**
Posts show. This doesn't even make sense, given the posts are fetched from your masto server. 

**Screenshots**
![d6cee011cb7266aa769888a42e61ea65f8835282a971089ddfc1e1f77b214a697abb225a557817bb3708d5e08a01d1dc5164d343a1175620b2d26567e32c45d2.jpeg](https://user-images.githubusercontent.com/44733677/221394820-3aaaa5e9-b09d-4897-b509-6b81a14eff6b.jpeg)

**Comment by sdubinsky** [comment]
Hi!  Have you tried this with other accounts, or just this one?  Mastodon generally only loads posts from remote accounts that you search for that are already in the local database.  Since nobody has interacted with Chris's account, no posts show up on moth.social.

**Comment by ThatOneCalculator** [comment]
Proof that a server that already fetched it can't show the posts:

![IMG_3181.png](https://user-images.githubusercontent.com/44733677/221399439-16f88ed8-1ca5-4301-9b45-cc3b921bcdbc.png)

![IMG_3182.png](https://user-images.githubusercontent.com/44733677/221399438-0a4e7600-5838-44d3-8724-acaa3084e88f.png)

**Comment by sdubinsky** [comment]
@ThatOneCalculator thanks!  We'll look into it.

**Comment by ThatOneCalculator** [comment]
Apparently Ivory has a similar problem. Are you both using a similar library?

**Comment by derspyy** [comment]
also you can't see replies under posts: 

![image](https://github.com/TheBLVD/mammoth/assets/65043391/1dcf8b15-874f-4328-9205-1dd4b5195007)
![image](https://github.com/TheBLVD/mammoth/assets/65043391/152cabed-27c0-4cfe-84d2-de1141c1c948)

**Comment by ThatOneCalculator** [comment]
This seems like a very strange issue, given the Mastodon API should treat user profiles and posts from remote Mastodon servers and remote non-Mastodon servers almost identically.

**Comment by derspyy** [comment]
except that mammoth is doing... broken requests DIRECTLY to the target instance...

![image](https://github.com/TheBLVD/mammoth/assets/65043391/a4eadccc-d7e9-462d-b5b8-83e183028014)
(i'm using eldritch.cafe)

maybe this is an attempt to load replies that aren't federated but it's a bad idea. moderation exists for a reason, god dammit!

**Comment by derspyy** [comment]
you should never:

- expect that a every server is running the same api.
- expect that the every original reply should be displayed.
- expect that the user will be able to interact with banned instances.

**Comment by ThatOneCalculator** [comment]
@bdecrem as a client, you should almost ***never*** query the remote instance directly for replies. This is a really bad practice (unless you're specifically a multi-API client like Kaiteki that uses dynamic adapters to bridge the gap. Which you're not.)

**Comment by derspyy** [comment]
clients like phanpy and mona offer an option to view a post using the original instance's api if it's on mastodon. however, it blocks interactions and has a clear distinction.

**Comment by derspyy** [comment]
also: you probably won't be able to see follower-only posts on remote instances, though i didn't test this.

**Comment by bvon** [comment]
> except that mammoth is doing... broken requests DIRECTLY to the target instance...
> 
> 
> 
> ![image](https://github.com/TheBLVD/mammoth/assets/65043391/a4eadccc-d7e9-462d-b5b8-83e183028014)
> 
> (i'm using eldritch.cafe)
> 
> 
> 
> maybe this is an attempt to load replies that aren't federated but it's a bad idea. moderation exists for a reason, god dammit!
> 
> 

Thanks for bringing this to our attention! Filed a ticket and the team will be reviewing.

**Comment by bvon** [comment]
This has been fixed in version 2.0, which should be released **very** soon!

**Comment by ThatOneCalculator** [comment]
@bvon if this is true, then this has NOT been resolved. As reiterated by @derspyy , clients should almost never query the remote server. Sincerely, a Fediverse platform developer and server administrator.

**Comment by derspyy** [comment]
i still have my concerns, but i consider _title issue_ fixed. that's why i wanted to bring it to a discussion, whenever those are enabled, instead of continuing here.

i voiced my ideas on the discord about showing a warning whenever you're loading from the remote instance, and possibly making it an option instead of the default behaviour. mammoth, however, is aimed at new mastodon users and so it's in its scope to be as seamless as possible.

when i talked to the devs, their main concern was about people not receiving the every single piece of content under profiles and posts, which kinda breaks the federation illusion. this will possibly stop being an issue for novice users as moth.social grows in size and caches more stuff, but right now it seemed crucial to the devs to show the most posts/replies/interactions.

it's ultimately a trade between content and stability, and the vision of the devs rightfully seems to lean into the former.

@bdecrem maybe you can explain a bit better. 😁
