### ISSUE TITLE
Support non-Mastodon instances (Akkoma, Pleroma, GotoSocial, etc.)

### ISSUE THREAD

**Issue by rjp** [TheBLVD/mammoth#27]
Currently Mammoth gives me an empty timeline on my Akkoma instance.

On my GotoSocial instance, it can't even complete the OAuth flow - I can login but then just get sent back to the "Add New Account" screen.

Since non-Mastodon instances are an important part of the Fediverse, and with more non-Mastodon instance types coming along (Wildebeest, Epicyon, Takahē, etc.), Mammoth should support these instance types as fully as it supports Mastodon instances.

**Comment by ShihabM** [comment]
Thanks, we'll look into this!

**Comment by overestimate** [comment]
Co-opting to explicitly request glitch-soc (a Mastodon fork) feature support; it has basic markdown formatting and allows changing certain limits, such as info slots on profile, bio length, name length, post length (which seems to be supported by Mammoth already), poll options, and other things I (likely) missed.

**Comment by bvon** [comment]
Issue seems to be resolved in Mammoth 2 [MAM-2993]
