### ISSUE TITLE
Video cannot be scrubbed

### ISSUE THREAD

**Issue by ringmaster** [TheBLVD/mammoth#271]
### Describe the bug

When viewing video in full-screen, Mammoth shows the video with a scrub bar, but that scrub bar is non-functional.  When touching the scrub bar, the video is unaffected.  When swiping on the scrub bar, the entire video moves and is dismissed.  It seems as though this behavior is caused by the gesture that dismisses a video overriding tap/swipe gestures on the scrub bar.

### To Reproduce

1. Go to a post that contains a video.
2. Tap the video to go full-screen.
3. Attempt to use the scrub bar by tapping in a specific location or scrubbing the head to a new location.

### Expected behaviour

When tapping on the scrub bar, the video should skip to the frame represented by that location in the scrub bar.  When scrubbing the video, the video should skip to the associated frame represented by the head location in the scrub bar.  When tapping the scrub bar or scrubbing the head, the video should remain in place on screen.  The video should only be dismissed when swiping the video area itself, not the bar.

### Screenshots

https://github.com/TheBLVD/mammoth/assets/127738/b8bdbd09-6eb1-4213-807e-b93e39dbad9a

### Instance address

N/A

### Device

iPhone 15 Pro

### OS

17.3 beta (21D5026f)

### Version

2.4 (368)

### Additional context

The instance address doesn't seem to be relevant, as this happens for all instances.  The instance of the example video is sportsbots.xyz

**Comment by ringmaster** [comment]
The example video I supplied seems like it didn't load fully for some reason, but this bug is also the case for videos that show an active scrub bar and display the video duration and play head location.

https://github.com/TheBLVD/mammoth/assets/127738/6703bcf4-1830-4702-b265-8085ed21f783

**Comment by bvon** [comment]
Ticketing the for the engineers. Thanks for the report!

**Comment by bvon** [comment]
Update: This has been address in Build 378!

**Comment by ringmaster** [comment]
Tested and fixed in 387! TYVM!!
