### ISSUE TITLE
Bug: Sluggishness with opening the app or swiping it away

### ISSUE THREAD

**Issue by decius** [TheBLVD/mammoth#28]
**Describe the bug**
I've notice some sluggishness the first couple of times that I opened or minimized the app. Basically I'd open the app, or swipe it away, and try to open it again, and my entire phone would freeze for about 15 seconds. 

It seems that this may clear up after a few minutes of use. I can't reproduce it anymore, but it was offputting when I first tried the app. 

**To Reproduce**
Install the app. Tell it you already have an account on mastodon (not moth.social), but when you get to the screen where you enter the server name, swipe the app away and try open it again.

Then enter the server name, and while authenticating to the server, swipe the app away and try opening it again. 

Then after you login, swipe the app away and try opening it again. 

**Expected behavior**
The app should instantly open or close when swiped away. 

**Screenshots**
I failed to grab one. There was a 15 second period of time when the app was suspended in mid-mimimize and you couldn't do anything to the phone, but that probably includes taking a screenshot. 

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: 16.1.1
 - Version [e.g. 22]: 1.0.2 - 114

**Comment by ShihabM** [comment]
Thanks for this, we'll look into it!
