### ISSUE TITLE
unable to find a post/user by link.

### ISSUE THREAD

**Issue by derspyy** [TheBLVD/mammoth#287]
### Describe the bug

when pasting a post's url to the search bar, it is expected for mastodon to find the post.
this isn't happening because the `resolve` parameter is not being set to true.

### To Reproduce

1. get a post url: `https://kolektiva.social/@piuvas/111733025336274898`.
2. paste it in the search bar in the discovery screen.
3. nothing.
4. press enter.
5. go to "posts".
6. also nothing.

### Expected behaviour

it shows the post both in regular AND posts search.

### Screenshots

![image](https://github.com/TheBLVD/mammoth/assets/65043391/e3e52202-4f27-4e31-ae7a-09b8456143d6)
![image](https://github.com/TheBLVD/mammoth/assets/65043391/dece268c-f23c-4161-ac46-798b71e52ae2)

### Instance address

kolektiva.social

### Device

iPhone 14 plus

### OS

iOS 17.2.1

### Version

build 474

**Comment by derspyy** [comment]
also happening for user searching.
![image](https://github.com/TheBLVD/mammoth/assets/65043391/e6f354e6-d188-4080-bad2-e154dc2afa2f)

**Comment by derspyy** [comment]
in the case the team would prefer this kind of lookup to be done in a separate place i suggest a little 🔗icon that reads from the clipboard?

**Comment by bvon** [comment]
The new beta addresses this, at least in part. Searching using https now works, in a way: it will show the user, but not direct to the actual post.

**Comment by derspyy** [comment]
![image](https://github.com/TheBLVD/mammoth/assets/65043391/d12cde39-d0d4-4e71-8722-258936e49e0b)

not working on my end. i'm on 380.

**Comment by derspyy** [comment]
my pr should fix it in its entirety, by the way. 

mastodon natively handles this kind of search, it's just not being called correctly on mammoth.
