### ISSUE TITLE
User's Likes and Bookmarks Not Displayed in Detail View

### ISSUE THREAD

**Issue by ScottCFrancis** [TheBLVD/mammoth#29]
**Describe the bug**

**To Reproduce**
1. Select a Post in the Timeline that's liked and/or bookmarked. 
2. Tap on it to view Detail. 
3. Your Like and/or Bookmark will not be displayed in the Detail view (e.g. the heart won't be filled and/or the bookmark icon won't be filled). 

**Expected behavior**
Your Like and/or Bookmark should be shown in the Detail view (e.g. the heart will be filled and/or the bookmark icon will be filled). 

**Screenshots**
See attached. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max, MacBook Pro M1 Pro (2021)
 - OS: iOS 16.2, macOS Ventura 13.2
 - Version [e.g. 22]: 1.0.2 (114)

**Additional context**
None. 

<img width="453" alt="Timeline View" src="https://user-images.githubusercontent.com/44330350/221446237-fdde17f5-64cf-40ea-a474-b2bdf65ab37a.png">

<img width="317" alt="Detail View" src="https://user-images.githubusercontent.com/44330350/221446269-837b6362-119c-47ec-bfcb-110a92b99d45.png">

**Comment by ShihabM** [comment]
Thanks for this! We'll look into improving this.
