### ISSUE TITLE
Larger Text in Detail View

### ISSUE THREAD

**Issue by ScottCFrancis** [TheBLVD/mammoth#30]
**Is your feature request related to a problem? Please describe.**
In my experience it's easier to distinguish the selected Post from others in the thread in Detail view when the selected Post is in a comparatively larger font. 

**Describe the solution you'd like**
In Detail view, display the Post in a comparatively larger font relative to other posts in the thread and/or otherwise visually distinguish it (though for me I think the larger font has to be part of the "how" here—the current bigger and blue icons are a start, but bumping the text size to match would finish the job). 

**Describe alternatives you've considered**
I really think it's all about the font size for me. 

**Additional context**
See Ivory's handling of posts (surprise) or the official Twitter client for examples of how this has been done well.

**Comment by ShihabM** [comment]
Great suggestion, thanks!

**Comment by ScottCFrancis** [comment]
Looks great in 1.1. Thanks!
