### ISSUE TITLE
Home Menu Doesn't Work If Home Not in Default (Leftmost) Tab Position

### ISSUE THREAD

**Issue by ScottCFrancis** [TheBLVD/mammoth#31]
**Describe the bug**

I can’t select anything below “Everything” in this menu if I put the Home item in the center tab position. 

This menu works perfectly if the Home item is in the default (leftmost) tab position.

**To Reproduce**
1. Put the Home item in the center tab position. 
2. Try to select any menu item below "Everything."
3. Nothing happens. 

**Expected behavior**
The selected menu item should trigger the associated view. 

**Screenshots**
See screenshot. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.2
 - Version [e.g. 22]: 1.02

**Additional context**
This menu works perfectly if the Home item is in the default (leftmost) tab position.

![image](https://user-images.githubusercontent.com/44330350/221447351-b4031a52-ef4d-4d48-8b60-00b8b19104f0.png)

**Comment by ShihabM** [comment]
Thanks for this, we will have a fix for this soon!

**Comment by ScottCFrancis** [comment]
Fixed in 1.1. Thanks!
