### ISSUE TITLE
No license for the issue tracker

### ISSUE THREAD

**Issue by nemobis** [TheBLVD/mammoth#33]
**Describe the bug**
Given the [README](https://github.com/TheBLVD/mammoth/blob/main/README) doesn't state a license, this issue tracker currently doesn't have a license. This means the ongoing discussions aren't freely licensed 

**Expected behavior**
Until a license is picked for the entire project, pick a temporary copyright status for the issue tracker which would allow later switches to your target license. Maybe CC-0?

*I release this comment under CC-0, MPL2 and AGPLv3*.

**Comment by ShihabM** [comment]
We'll resolve this soon, thanks!

**Comment by bdecrem** [comment]
got it.

**Comment by bdecrem** [comment]
we are doing CC0 for the issue tracker. This means all content here on the issue tracker is public domain. Have at it, y'all!
