### ISSUE TITLE
Add information on how to contribute and copyright status on the website

### ISSUE THREAD

**Issue by nemobis** [TheBLVD/mammoth#34]
**Describe the bug**
I couldn't find any link to the repository from the website, https://getmammoth.app. This conveys an image of a community-hostile project which doesn't believe in user freedom nor collaboration, while the intention seems to be the opposite.

**Expected behavior**
Even before the project releases its code under a free license, a section can be added to https://getmammoth.app/details.html inviting contributions with a link to this repository, with a clarification that the app is currently proprietary but is expected to become FLOSS soon.

*I release this comment under CC-0, MPL2 and AGPLv3*.

**Comment by ShihabM** [comment]
Great idea!
