### ISSUE TITLE
Quote a toot

### ISSUE THREAD

**Issue by Krit1960** [TheBLVD/mammoth#36]
The possibility to quote a toot, so boost it with the possibility to add text above.

**Comment by MacaylaMarvelous81** [comment]
This would definitely be great! However, I’m not sure that Mastodon itself has this feature at the moment.

**Comment by Krit1960** [comment]
I don't think so, but other clients already do have this. I think it is of great value/

**Comment by ShihabM** [comment]
We will take this onboard, thanks!

**Comment by echidistanti** [comment]
I would like to see a "quote-toot" mechanism implemented on mammoth, similar to the one used by "iceCubes". This feature should enable me to include a mention of another user's toot and a link to the original toot. Moreover, the preview of the toot should display a small avatar, the name of the original user, and the content of the toot.

I believe that a "quote-toot" mechanism would be an essential tool that allows me to share content from other users on the platform while giving credit to the original creator. By mentioning the user and providing a link to the original toot, I can easily direct my followers to the source of the content.

Having a small avatar and the username of the original user in the preview of the toot would also be helpful in giving context and credit to the original creator. This feature can also help me identify and follow new users whose content I find interesting.
