### ISSUE TITLE
Audio Support

### ISSUE THREAD

**Issue by ringmaster** [TheBLVD/mammoth#365]
### Is your feature request related to a problem? Please describe.

I am not able to post audio from my phone, nor am I able to play back audio that has been posted via the Mastodon web client. 

### Describe the solution you'd like.

I would like to be able to select audio files from Mammoth to post to my Mastodon instance. I would also like to be able to click the playback button on audio files in Mammoth and hear audio along with operating playback controls. 

### Describe alternatives you've considered.

I posted audio to Mastodon via the web UI, but then when I returned to Mammoth, the file would not play. It just showed a non-working play button. 

### Additional context.

See https://mastodon.social/@ringmaster/111824271565558044 for a port with audio.
![This is what it looks like in Mammoth, and it does not play](https://github.com/TheBLVD/mammoth/assets/127738/4a6e0ea8-6c12-42ca-8ca3-eb96f3bcf4f7)

**Comment by derspyy** [comment]
will close this issue because the audio files are playing correctly, but i'll start an internal discussion about adding a built-in audio recorder, upload, player, etc.
