### ISSUE TITLE
Suggestion: Never scroll unless the user asks for it

### ISSUE THREAD

**Issue by decius** [TheBLVD/mammoth#37]
**Is your feature request related to a problem? Please describe.**

The app will sometimes scroll up to the top of a feed on it's own even though the user hasn't requested this and may not desire it. This is one of my peevs with the Twitter app. 

For example, take the following steps:
1. Click on a person in your feed to visit their profile.
2. Scroll way down in their profile so you the app has to load posts from the server a few times. 
3. Click on a post. (For example, find a post where the user has replied to someone and click on it to see the whole thread.)
4. Then go back to the profile, clicking the "< Profile" link. 
5. Wait about 3 seconds and ... *poof* the app scrolls back to the top of the profile. You are no longer staring at the place in the chronology that you were before, and if you want to get back to it you need to scroll way down again. 

**Describe the solution you'd like**
I'd rather you did not scroll to the top of a feed unless the user made a gesture indicating that this is desired. 

**Describe alternatives you've considered**
Do people like this "automatically scroll to the top of the feed" behavior? Twitter's app seems to do it too. Perhaps make it configurable so those of us who don't like it can turn it off? I went looking but didn't see an obvious knob for this in your settings.

**Comment by ShihabM** [comment]
Thanks for this, sounds like a bug, we'll look into it.
