### ISSUE TITLE
Justify posts to screen width

### ISSUE THREAD

**Issue by tollfree** [TheBLVD/mammoth#38]
Hi folks,
Such a great app!
I propose to add a way to show the feed without empty spaces I marked red on this screenshot:
![Monday, 27 Feb 2023 05:47:26](https://user-images.githubusercontent.com/5585001/221622313-f9181ef3-f938-4464-8890-a97d70888bb8.png)
Somehow it looks like Mastodon feed:
![Monday, 27 Feb 2023 05:50:50](https://user-images.githubusercontent.com/5585001/221622586-d5767156-9dfa-4afa-b8b0-88b29750083a.png)

What you think?

**Comment by ShihabM** [comment]
Great idea! We'll look into it.

**Comment by mcchots** [comment]
Also if this were implemented, if the bookmark icon could come out of the ... menu and on to the main post, it would be great.
