### ISSUE TITLE
Character limit of 500 characters prevents sending

### ISSUE THREAD

**Issue by loma-one** [TheBLVD/mammoth#39]
**Describe the bug**
According to the W3C specification, there is no character limit for AP when creating and sending content. However, they provide for an upper limit of 500 characters. They probably took this information from the Mastodon specification. However, this is only an interpretation of AP and not one according to W3C. The majority of Fediverse projects (also in the Mastodon branch) therefore usually support between 280 - 5000 characters. Friendica has no character limit.

**To Reproduce**
1. create new post
2. post has more than 500 characters
3. send button is greyed out/not supported

**Expected behavior**
Sending content with more than 500 characters is supported

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone6]
 - OS: [e.g. iOS16.3.1]
 - Instanz: https://loma.ml (Project Friendica)

**Additional context**
[W3C Spezfication](https://www.w3.org/TR/activitypub/)

**Comment by sdubinsky** [comment]
Support for other parts of the fediverse is on our roadmap, but we aren't there yet.  We'll let you know when we do!  For now, since Mastodon limits you to 500 characters per post, so do we.

**Comment by loma-one** [comment]
Thank you very much for the answer.
Question: So it is an artificial character limit caused by the APP, correct?

Note: Friendica, as part of Fediverse, works fully compatible with Mammuth, except for the character limit. It will be good if they remove the artificial limit in due course.

**Comment by sdubinsky** [comment]
This is a limitation imposed by the Mastodon software, not by Mammoth.

**Comment by bvon** [comment]
I believe this issue was mostly addressed by adding threaded posting as a workaround for Mastodon's 500 character per-post limit.
