### ISSUE TITLE
Empty notification screen

### ISSUE THREAD

**Issue by yordiak** [TheBLVD/mammoth#41]
Even though I receive properly notifications when I open the app the notification page is empty

 - Device: Iphone 11
 - OS: 16.3.1
 - Version: 1.0.2, build 114

**Comment by sdubinsky** [comment]
We'll take a look at this!  In the future, however, can you use the bug report template provided?  It makes it a lot easier for us.

**Comment by sdubinsky** [comment]
@yordiak can you supply more details?   What kind(s) of notifications are you receiving?

**Comment by yordiak** [comment]
When the screen is off I receive both "mentioned" and "like" notifications as a badge notification. But when I open the app and navigate to the notification tab, then no notification is displayed (the notification tab is empty)

**Comment by sdubinsky** [comment]
Thanks!  I've passed it on to the developers and we'll get back to you when it's fixed.
