### ISSUE TITLE
Add indicator to account switcher

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#43]
**Is your feature request related to a problem? Please describe.**
Having the same profile picture on multiple accounts makes it difficult to identify which account is currently active. And this gets even more cumbersome should a user add even more accounts. 

**Describe the solution you'd like**
Add indicator to account switcher to display currently active account. 

**Thinking further on  account selection/management:**
Since Mammoth currently uses color in account switcher it would be a nice touch also for consistency to have the same colors applied in **Settings > Accounts** section too. So having blue and purple in switcher these colors would also be shown under their respective accounts in settings menu.

**Comment by sdubinsky** [comment]
Great idea!  I've passed it along.
