### ISSUE TITLE
Handle paragraphs

### ISSUE THREAD

**Issue by Imzxhir** [TheBLVD/mammoth#439]
### Describe the bug

I noticed that mammoth does not really handle paragraphs well and most of the text is just joined up together without any spacing. This does not happen with other apps like Ivory or Mona or even the Mastodon web app.

### To Reproduce

1. Go to this [post](https://bark.lgbt/@rail_/112010547494858399) on Mammoth
2. Compare the post and between other apps

### Expected behaviour

Mammoth should implement some spacing between paragraphs.

### Screenshots

Ivory: 
![IMG_0395](https://github.com/TheBLVD/mammoth/assets/98621617/099d74dc-449b-4afb-8afd-1037f8aac821)

Mona:
![IMG_0397](https://github.com/TheBLVD/mammoth/assets/98621617/45d8f009-1e6c-419a-95d1-a8d58f6bb2bb)

Mammoth:
![IMG_0396](https://github.com/TheBLVD/mammoth/assets/98621617/2a1e54a0-f307-4f25-bdfc-16b506397960)

### Instance address

blobfox.coffee

### Device

iPhone 12

### OS

iOS 17.3.1

### Version

2.8

**Comment by derspyy** [comment]
looking into it >:P
