### ISSUE TITLE
Improve how content warning is displayed on timeline

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#44]
Current implementation breaks up timeline scrolling with too much unnecessary space on CW posts with text only content      

![image](https://user-images.githubusercontent.com/120338442/222915724-3702df99-b5eb-4651-b97c-c7c87d7ec4bc.jpeg)

**Describe alternatives you've considered**

**Ice Cubes**

![image](https://user-images.githubusercontent.com/120338442/222915743-73b9c2bf-5697-48ab-b6af-735f145daca6.jpeg)

**Ivory**

![image](https://user-images.githubusercontent.com/120338442/222915756-9306b2db-e0d1-4190-840f-305259be1ba8.jpeg)

**Mona**
 
![image](https://user-images.githubusercontent.com/120338442/222915775-b8f616cb-b793-4ff3-9161-a1aec88a3ed0.jpeg)

**Comment by bdecrem** [comment]
thanks for this.  filing the issue now. mam-945
