### ISSUE TITLE
Tab bar icons remain visible 

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#46]
1. Go to **Settings >Gestures** 
2. Disable **Tab Quick Switch Icons** 
3. Check main UI and Icons are now removed. 
4. Back to **Settings >Gestures**
5. Disable **Tab Quick Switch** 
6. Re-enable **Tab Quick Switch**
7. Check tab bar and icons are now visible, even though the toggle for **Icons** is still disabled. 

**Expected behavior**
Tab bar icons should remain disabled since toggle is still in off position. 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.3.1 (20D67)
 - Version: 1.1 Build 119

**Comment by bdecrem** [comment]
thanks pjolt. I filed the internal issue for this, mam-994

**Comment by nvella** [comment]
QA confirmed fixed in development build 133.
