### ISSUE TITLE
Using camera in compose view fails without prompting the user when camera access is off 

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#47]
**Describe the bug**
When app permission for camera access is set to off and tapping the camera icon in compose view nothing happens. 

**To Reproduce**
1. Go to device main **Settings** and find **Mammoth** 
2. Disable **Camera** access
3. Open **Mammoth >Compose >Tap on Camera** to take a picture

**Expected behavior**
A prompt that informs the user that proper app permission is missing for camera and asking if the user wants to grant access. 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro & iPad Air M1
 - OS: iOS 16.3.1 (20D67) & iPadOS 16.3.1 (20D67) 
 - Version: 1.1 Build 119

**Comment by sdubinsky** [comment]
Good thinking.  We'll see what we can do.
