### ISSUE TITLE
Tapping on a notification shows wrong content

### ISSUE THREAD

**Issue by dminca** [TheBLVD/mammoth#48]
**Describe the bug**
Tapping on a liked post shows you something entirely different but not the liked post

**To Reproduce**
1. Go to All Activity
1. Tap on a recently liked post by someone
1. See error

**Expected behavior**
Show the actual liked post

**Screenshots**
![IMG_8230](https://user-images.githubusercontent.com/5355219/222928616-ad7f113a-95b5-47df-8abd-812f8a567f1d.PNG)

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5355219/222928855-e1822d2b-8746-4bea-a9e2-e9bf1670c9fa.png">

**Smartphone (please complete the following information):**
 - Device: iPhone12Pro
 - OS: 16.3.1
 - Version: 1.1 Build 119

**Additional context**
The 2nd screenshot shows the expected behavior on a desktop.

**Comment by sdubinsky** [comment]
Thanks for the report!  I've passed it on and we'll look into it.
