### ISSUE TITLE
Post with poll result missing percentage (%) in detailed view

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#49]
**Describe the bug**
When going into a post detail for a poll that has ended no percentage (%) sign is shown for the different results. 

**To Reproduce**
1. Go to **Activity tab** and view a post with results for a poll that has ended
2. Confirm that % is shown correctly 
3. Tap on the post to get **Detail** view 
4. Percentage (%) signs can be seen very briefly before they disappear

**Expected behavior**
Percentage (%) should be visible in alao in detail view.   

**Screenshots**
https://user-images.githubusercontent.com/120338442/222956524-ad244b84-dd0d-4218-8b72-077adba568eb.MOV

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro & iPad Air M1 
 - OS: iOS 16.3.1 (20D67) & iPadOS 16.3.1 (20D67)
 - Version: 1.1 Build 119

**Comment by pjolt** [comment]
https://user-images.githubusercontent.com/120338442/222956997-89f398e5-6005-4264-b6ee-77fd40f61f2d.MOV

**Comment by sdubinsky** [comment]
good find!  We'll fix this.

**Comment by bvon** [comment]
Fixed in version 2
