### ISSUE TITLE
Implementing a Mammoth-compatible server

### ISSUE THREAD

**Issue by icyphox** [TheBLVD/mammoth#494]
Hi,

I'm currently writing code to add Masto API support (mostly to work with Mammoth, for now) to an [existing ActivityPub server](https://humungus.tedunangst.com/r/honk). I'm running into a rather perplexing issue and I was hoping you could shed some light what's causing it.

Here's the order of endpoints I've implemented so far:
- GET /api/v1/instance
- POST /api/v1/apps
- POST /oauth/authorize
- POST /oauth/token
- GET /api/v1/accounts/verify_credentials

Now, Mammoth goes through all of these just fine—the OAuth flow etc. The /api/v1/verify_credentials call is successful (200), but Mammoth seemingly errors out after that with a pop-up: "The operation could not be completed. (Unable to log into account error 401.)"

So that error originates from this line here: https://github.com/TheBLVD/mammoth/blob/e9f9aafbd36d0d5156190f01bc92354ef5098a73/Mammoth/Managers/AccountsManager/AcctHandler.swift#L84
but I'm not quite sure why. Seems like the `if let account = statuses.value` check fails above—what exactly does that mean here?

Any insight would be really helpful, thanks!

**Comment by derspyy** [comment]
though IDK why it says statuses (maybe copy pasted from somewhere else), this is because verify_credentials should return the Account object. are you sure it's being returned?

**Comment by icyphox** [comment]
Oh, thanks for the hint. I didn't realise that a few of those fields in the Account object were mandatory! I adjusted my server code to return the necessary fields and it logged in! I can close this now, but I hope you don't mind if I pop back in to ask for pointers.

Thanks again!

**Comment by derspyy** [comment]
haha, no worries. if anything, you can join the discord and ask for help there. we'll be quicker to answer you :p
