### ISSUE TITLE
MacOS client not loading Activity and Messages

### ISSUE THREAD

**Issue by dminca** [TheBLVD/mammoth#50]
**Describe the bug**
Activity and Messages tabs are gone after navigating through the app for some time.

**To Reproduce**
1. Open the Mammoth app
2. Reply to an Activity
3. Go back home

**Expected behavior**
Activity and Messages must always load

**Screenshots**
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/5355219/222961488-f5973a77-6093-4b16-afe1-225846162e5d.png">

**Smartphone (please complete the following information):**
 - Device: MacBook Air
 - OS: MacOS Ventura 13.2.1 (22D68)
 - Version: 1.1 Build 119

**Additional context**
Sometimes it's hard to reproduce, but if it helps, I've kept the app dormant on the Mac for 2-3 days, and after opening the Mac lid to check notifications, tapped on my latest notification and then went back to my timeline; afterwards they weren't loading anymore.

**Comment by bvon** [comment]
This has been fixed in version 2
