### ISSUE TITLE
Application 1.1 build 119 crashes at launch

### ISSUE THREAD

**Issue by C-Duv** [TheBLVD/mammoth#54]
**Describe the bug**

The application crashes on startup (first launch or re-open when already launched).

**To Reproduce**

1. Click the Mammoth icon on the SpringBoard to open the application.

**Actual result**

The application opens and closes a second later.

After a few tries it sometimes stays open and works.

**Expected behavior**

The application should open and stay opened.

**Screenshots**

Here is a video recording where I try several times to open the application.

At third and fourth try I aim for the right-most icon of the bottom bar hoping a screen change will avoid the crash to occur.

https://user-images.githubusercontent.com/1466273/223566395-9ee6c38a-00b5-4438-838c-c9edacf85d6c.mp4

**Smartphone:**

- Device: iPhone7
- OS: iOS 14.8.1
- Version: 1.1, build 119

**Additional context**

Tried iPhone complete restart: same issue.

Installed the application on 2023-02-25 and it was working fairly fine (just some scrolling issues) until I updated it on 2023-03-05 and got this issue.

**Comment by C-Duv** [comment]
Update: The crash still occurs on version 1.2, build 128.

**Comment by bvon** [comment]
This should be resolved in Mammoth 2.
