### ISSUE TITLE
iOS app substitutes HTTPS for HTTP URLs in profile links.

### ISSUE THREAD

**Issue by dchansen42** [TheBLVD/mammoth#56]
**Describe the bug**
In my profile, I have a link which uses HTTP. I noticed that when I press on it in the Mammoth app, it opens the URL with HTTPS instead. Which is normally a fine assumption these days but in some cases, such as this one, that can take you to a completely unrelated page.

**To Reproduce**
1. Go to Profile.
2. Tap on "Info and Links".
3. If you have a profile link with an HTTP URL and press on it, the app will substitute HTTPS. Which, in my case, takes you to a completely different page.

**Expected behavior**
I would expect it to open the URL using the stated protocol (http).

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 -Device: iPhone 13
-OS: iOS 16.3.1
-Version: 1.1
-Build: 119

**Additional context**
I like this app. Thank you for your work!

**Comment by sdubinsky** [comment]
Thanks for the report!  Can you link your profile please?

**Comment by dchansen42** [comment]
Certainly, it is https://mastodon.sdf.org/@dchansen / @dchansen@mastodon.sdf.org .

**Comment by bvon** [comment]
Closing [refer to MAM-1035]
