### ISSUE TITLE
Toggle to hide content that has been filtered does not work

### ISSUE THREAD

**Issue by SuperFola** [TheBLVD/mammoth#562]
### Is your feature request related to a problem? Please describe.

I’m filtering a few hashtags and words, because I don’t want to hear from the bird site in my feeds. However on Mammoth there is a post with an overlay saying that something has been filtered.

### Describe the solution you'd like.

I’d like to be able to toggle this behavior on and off: show that something has been filter or just don’t show the filtered content.

**Comment by derspyy** [comment]
hmm i think this may be residual from when filtering was done client-side... can you send a screenshot of that overlay?

**Comment by SuperFola** [comment]
It looks like this when my Twitter filter hits:

![image](https://github.com/TheBLVD/mammoth/assets/10694085/92a6d292-a449-4d8e-93e4-de84f5656c56)

**Comment by derspyy** [comment]
oh! this is a filter option from mastodon. you should be able to enable "Hide Completely" on the filter's options. : )

**Comment by SuperFola** [comment]
Ah yes! The thing is, I already have "hide completely" on all my filters:

![image](https://github.com/TheBLVD/mammoth/assets/10694085/94e7b757-186c-4ea3-b678-a388d301874a)

**Comment by SuperFola** [comment]
I didn't think of checking there too, but it's also on "hide completely" (with all the extras turned on)

**Comment by derspyy** [comment]
i think the issue is that we're just not hiding the post when it has that flag. will totally be looking into that.
