### ISSUE TITLE
Option to scroll to top on local and federated feeds

### ISSUE THREAD

**Issue by SuperFola** [TheBLVD/mammoth#563]
### Is your feature request related to a problem? Please describe.

I like reading the local and federated feeds but they get so many messages that I always need to take 5 to 10 minutes waiting for them to load and scroll to the top, or else I’m stuck a few days behind (and it will only get worse each time). 

### Describe the solution you'd like.

I’d like to be able to scroll to the latest posts without loading all the posts in between. Say I’m 5 days behind, I don’t want to load 1000+ post, only the last 20+ and scroll automatically to them. Then I can scroll to the bottom to get the older ones.

### Describe alternatives you've considered.

Refreshing the feed and waiting for messages to load: very long and a bunch of api hits that could be avoided.

### Additional context.

![IMG_0062](https://github.com/TheBLVD/mammoth/assets/10694085/bf1279c4-ff82-40ab-a3c3-3cea717c9a15)

here I’m already two days behind and it stops loading at 300-400 messages, then I have to scroll to the top and do it again until I’ll up to date.

**Comment by derspyy** [comment]
we currently have a shortcut for refreshing the feed when you double-tap "Home", down there, though there are some issues with it, that we're addressing on #568 ☺️

**Comment by SuperFola** [comment]
I didn't know about this feature, thanks!
