### ISSUE TITLE
Post timestamp missing in most posts

### ISSUE THREAD

**Issue by alexqzd** [TheBLVD/mammoth#564]
### Describe the bug

The timestamp is missing in the majority of posts. Most commonly happens with posts that appear after refreshing the timeline.

### To Reproduce

1. Open the app
2. Refresh the timeline

### Expected behaviour

All posts have a timestamp

### Screenshots

![IMG_3600](https://github.com/TheBLVD/mammoth/assets/5033308/b65b7665-9be9-4496-9a54-b37b6bd90b03)

### Instance address

mastodon.social

### Device

iPhone 15 Pro Max

### OS

iOS 17.4.1

### Version

2.12.1 - 462

**Comment by derspyy** [comment]
i haven't seen this! can you send logs through the app settings, right after this happens?

**Comment by alexqzd** [comment]
Yesterday I reinstalled the app to get a cleaner state before sending the logs and I haven’t been able to replicate the issue since (it used to happen every time). I guess I should have done that first haha. We can close the issue for now and if I ever encounter that again, I’ll let you know. Thanks!

**Comment by alexqzd** [comment]
I just experienced something similar, all the posts in the For You tab have “0S” as timestamp
[Mammoth Log.txt](https://github.com/TheBLVD/mammoth/files/15281330/Mammoth.Log.txt)

https://github.com/TheBLVD/mammoth/assets/5033308/a937ad3a-6e79-4162-bb1a-4b7b8aaff72d

**Comment by derspyy** [comment]
hmm... this would mean "0 weeks", right?
could you try unsubscribing from your smart lists and subscribing again?

**Comment by alexqzd** [comment]
I did that and it's been working fine for the last few days, thanks!
