### ISSUE TITLE
macOS client support for Intel macs

### ISSUE THREAD

**Issue by foss-** [TheBLVD/mammoth#57]
**Is your feature request related to a problem? Please describe.**
Currently the app only runs on M1 or later macs.

**Describe the solution you'd like**
Also support Intel macs.

Maybe this is out of scope, but it would be really nice for people using devices older than Nov 2020 to be able to also use mammoth.

**Comment by sdubinsky** [comment]
Hey!  Right now, Apple silicon macs are running the iOS app, but intel macs will require an actual mac build.  That's on the roadmap, but we don't have a specific timeline yet.  Stay tuned!
