### ISSUE TITLE
Cross p-device timeline syncing not working

### ISSUE THREAD

**Issue by jasonkarns** [TheBLVD/mammoth#573]
### Describe the bug

I originally thought this would be a feature request u til I saw #11 and #14 so I presume this is expected to already work.

I have mammoth on my iPhone and iPad. However my current read status between timelines (ie, my scroll position) isn’t kept in sync between devices. 

### To Reproduce

1. Open mammoth on device 1 (say iPhone)
2. Read to “latest” on my following timeline.
3. Wait a few hours
4. Open mammoth on iPad.
5. Scroll position in timeline does not match iPhone.

### Expected behaviour

I would expect that the iPad (picks up) where I left off on the iPhone and vice versa. Whichever device was used most recently would have its scroll/read position mimicked to other devices when they are opened.

### Instance address

Indieweb.social

### Device

iPhone 13, iPad 10

### OS

iOS 17.5

### Version

2.11.1

**Comment by derspyy** [comment]
hey... the other issue wasn't supposed to have been closed... we still don't have this feature! i'll reopen that and close this one, make sure to subscribe to that!

**Comment by jasonkarns** [comment]
Thanks!
