### ISSUE TITLE
Hide list posts from home page

### ISSUE THREAD

**Issue by Zabriskije** [TheBLVD/mammoth#588]
### Is your feature request related to a problem? Please describe.

Right now, to disable list posts from appearing on the home page, one has to do it via web (List settings → Hide these posts from home).

### Describe the solution you'd like.

It would be nice to have the option to do it directly in the app.

**Comment by derspyy** [comment]
oh, that's a good one : )

**Comment by inb4ohnoes** [comment]
This is implemented in App Store 2.14 as an option in long hold menu on list title. In the future list management would get better UI in general, but closing this as solved.
