### ISSUE TITLE
iOS app crashes when trying to click an account link on some user's profile page.

### ISSUE THREAD

**Issue by dchansen42** [TheBLVD/mammoth#59]
**Describe the bug**
The iOS app crashes when trying to click an account link from some user's profile page. I initially found this bug when clicking account links from a follower's follower's profile page but in further testing, while writing this report, I found that it is not that limited. But for the more difficult to reproduce examples, this information may still be relevant. Attempts to reproduce this are not consistent in number of times that one must attempt to click the link. Sometimes it can be dozens of clicks or one. The initial crash, @lastcelebration, I had spent some time reading down their feed before scrolling up to look at the referenced account. 

Sample profiles:
supernova
@caerula@universeodon.com
    link @qakqed 

Luke Buckmaster
@lukebuckmaster@mastodon.au
   link @GuardianAus.
   link @FlicksAustralia
   link @NME

James Cridland
@james@bne.social
     link james@crid.land
       
@lastcelebration@fosstodon.org
    link @mlastcelebratio@masthead.social

**To Reproduce**
1. Go to your profile > Followers.
2. Tap on a follower in the list. First three samples are from Bart Decrem (@bart@moth.social).
3. Go to Followers on that profile.
4. Scroll down to a follower with a link in their profile. (Though, see above.)
5. Tap on the follower to get to their profile page and then try tapping on an account link in their profile.
6. If the app does not crash within a few presses, try scrolling down their feed a bit then go back up to tap the link.

**Expected behavior**
To not crash.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 16.3.1
 - Version [e.g. 22]: 1.1 build 119

**Additional context**
 In testing I have since determined that all of these happen to have links to invalid accounts on their profiles.
Also, supernova seems to be the most reliable test to generate a crash. I can generate a crash from that account simply by launching fresh, using search to find the account (@caerula@universeodon.com), selecting the profile and then tapping the @qakqed link a couple of times. I do not know if that suggests that this account exhibits a different bug or just an easier to trigger sample of the same bug.

**Comment by sdubinsky** [comment]
Oh, nice find!  We'll get this fixed right away.

**Comment by bvon** [comment]
Issue resolved [see MAM-1032].
