### ISSUE TITLE
Adding animated gif fails in error

### ISSUE THREAD

**Issue by Depechie** [TheBLVD/mammoth#593]
### Describe the bug

Each time I select an animated gif to be added to a toot, through the GIF button, I get an exception.

### To Reproduce

Click enter new toot
Select gif button below
Select gif

### Expected behaviour

The gif should be added

### Screenshots

![IMG_3492](https://github.com/TheBLVD/mammoth/assets/351693/2108bd00-0390-43cd-9389-443e2e629b9a)

### Instance address

Dotnet.social

### Device

iPhone Xr

### OS

17.5.1

### Version

2.13 build 467

**Comment by kernjackson** [comment]
Looking at the [Mastodon API Documentation](https://docs.joinmastodon.org/methods/media/#202-accepted) Version `4.0.0` introduced version 2 of the media methods. Version 1 is now deprecated and the new version returns a `202` for larger images. The documentation indicates using `GET /api/v1/media/:id` to check the status of the attachment when using `v2`.

A quick fix would be to revert to `v1` (see [Commit #533](https://github.com/TheBLVD/mammoth/commit/9565dc2b9717b4b0d09a89fc4b6e1decf8d317a8))  as I was able to send an animated GIF using `/api/v1/media/:id`

![IMG_2457](https://github.com/TheBLVD/mammoth/assets/6172851/d1f56fbc-27f7-43b2-a9a5-be4af855158a)

**Comment by derspyy** [comment]
would be even better to just let the 202 work the same as a 200, right?

**Comment by kernjackson** [comment]
Yes, handling the `202` as a success is definitely the better overall solution.

I'm very new to the project and there's a lot going on in `NewPostViewController` so please bear with me 🙂. It looks like we're using a modified version of MastodonKit that adds a `Result` type with `success` and `failure` cases. Extending that to handle a `pending` case would allow us to get the results and then check the status as mentioned in the documentation.

**Comment by derspyy** [comment]
> Yes, handling the `202` as a success is definitely the better overall solution.
> 
> 
> 
> I'm very new to the project and there's a lot going on in `NewPostViewController` so please bear with me 🙂. It looks like we're using a modified version of MastodonKit that adds a `Result` type with `success` and `failure` cases. Extending that to handle a `pending` case would allow us to get the results and then check the status as mentioned in the documentation.

or maybe start considering every `2XX` as success?

**Comment by inb4ohnoes** [comment]
This is technically solved in the latest App Store release (wait a bit after media finishes uploading), and will be accounted for in UI in the next App Store release. Closing this as fixed.
