### ISSUE TITLE
Expanded Browser Support

### ISSUE THREAD

**Issue by kernjackson** [TheBLVD/mammoth#598]
### Is your feature request related to a problem? Please describe.

When I click a link it currently only opens in app or in Safari based on my settings.

### Describe the solution you'd like.

I want a settings screen to indicate which app I want external links to open in (Mammoth, Safari, Chrome, FireFox, DuckDuckGo, etc). I should also be able to enable Reader Mode by default when the open link setting is set to Mammoth.

**Comment by derspyy** [comment]
#600 merged!
