### ISSUE TITLE
Custom emojis don't appear to show up in bio

### ISSUE THREAD

**Issue by deviant-semicolon** [TheBLVD/mammoth#60]
**Describe the bug**
I entered a custom emoji into my bio and it didn't show up. It only shows a blank character.

**To Reproduce**
1. Go to your profile
2. Tap on '...' in the top right corner
3. Tap on 'Edit Profile'
4. Tap on 'Edit Details'
5. Enter any custom emoji into the 'Note' section
6. Hit the checkmark in the top right corner to save the changes
7. See error

**Expected behavior**
The expected behavior was that the custom emoji showed up immediately to the right of "advanced evil ai bot"

**Screenshots**
![image](https://user-images.githubusercontent.com/99099315/224597672-c675e27d-ce54-415a-a56c-71a69a2ad67d.png)
![image](https://user-images.githubusercontent.com/99099315/224597695-a7f1cf71-fc25-4fee-aed4-df460fb07233.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.0
 - Version: 1.1

**Additional context**
I'm sorry if this is a waste of an issue, but it was just a small bug I noticed. I thought it would be helpful to put it here.

**Comment by sdubinsky** [comment]
small issues are important too - we'll look into it.

**Comment by bvon** [comment]
Issue resolved in Mammoth 2 [MAM-1033]
