### ISSUE TITLE
Switching media style results in UI changing from settings to home

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#61]
**Describe the bug**
Setting media style to **large or small** changes UI from settings menu to home whereas setting media style to **none** keeps the user in settings menu. 

**To Reproduce**
1. Open **Mammoth** and go to **Settings**
2. Select **Post Appearance**
3. Set **Media Style** to **Large** 
5. UI switches over to **Home**
6. Repeat the process and change **Media Style** to **Small**
7. UI again switches over to **Home**
8. Repeat the steps and change **Media Style** to **None**
9. UI does not change, so still displays the **Settings >Post Appearance** view. 

**Expected behavior**
Changing media style should not switch the view from settings to home.  And if this is working as intended then consider also switching to Home view when setting media style to None. That would feel more consistent to me at least in behaviour. 

**Screenrecording**
https://user-images.githubusercontent.com/120338442/224782771-d2f6ed2c-880a-48cc-86e8-75c99a8eb4ca.MOV

**Device:**
 - Device: iPhone 13 Pro & iPad Air M1
 - OS: 16.3.1 (20D67) 
 - Version: 1.2 Build 128

**Comment by sdubinsky** [comment]
thanks for the report!

**Comment by bvon** [comment]
Closing ticket [MAM-1034]
