### ISSUE TITLE
An odd issue which prevented me from being able to submit a lengthy post with images.

### ISSUE THREAD

**Issue by dchansen42** [TheBLVD/mammoth#62]
**Describe the bug**
I encountered a problem two days ago with a lengthy post, on my phone, which included 3 screenshots. Many attempts later, which also included re-wording the message to a lesser character count,  I finally tried adding the pics first, then the text. This started to look promising but then the pics disappeared from the editor view. I tried to post anyway, resigned to adding the pics in a follow up post, when I received a message about a media upload in progress. Approximately 10 minutes later the media upload was still in progress. I copied and pasted the post to another client and it published right away.

**To Reproduce**
2. Tap on '....'
 I have not tried to reproduce this error yet.

**Expected behavior**
If there really was a media upload in progress then perhaps some sort of visual representation (A progress bar?) to let the user know that some action is happening.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 16.3.1
 - Version [e.g. 22]: 1.1 build 119

**Additional context**
The post is https://mastodon.sdf.org/@dchansen/110005696140676419

**Comment by sdubinsky** [comment]
We'll take a look!

**Comment by fjcuadrado** [comment]
Hi everyone.

I could reproduce the same issue in my iPhone.

Like @dchansen42 said, you only have to upload some image, before or after writing a lengthy text. The image disappears and if you try to publish the toot, mamooth warns you about a media upload in progress even when the image is already uploaded. If you click to publish the toot without media, the toot will be published with the media.

It’s a very annoying issue, I hope you could fix it soon. 

Thanks for your incredible work.

**Comment by NathanRLiu** [comment]
Thanks @fjcuadrado, I've made a note in our internal issue tracker that you're also experiencing this issue; this will let the engineering team know that it's more common than we previously thought. Will update back when the problem gets fixed!

**Comment by dchansen42** [comment]
If it helps, and is relevant, I did not have "Threader mode" (Settings > Actions > Composer >) enabled at the time.

**Comment by bvon** [comment]
Issue appears resolved in Mammoth 2.
