### ISSUE TITLE
Long tap on follow on profile page can result in option to unfollow even though account is not followed.

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#63]
Going into a profile page and long tap on the **Follow** button sometimes incorrectly displays a option to **Unfollow** even though the account is not one you follow. 

**To Reproduce**
1. Go into a profile page of an account that you do not follow. 
2. Long tap on **Follow**
3. Either an option to **Unfollow** appears **or** a sub-menu with options to mention, send message, or see recent media of a user appears.  
4. When the **Unfollow** option appears **Pull down to refresh** on profile page, or press back and then long tap **follow** again and the sub-menu with options for mention, message, recent media etc appears. 

**Expected behavior**
**Unfollow** should not be a option for account that is not  followed.

**Screenrecording**
https://user-images.githubusercontent.com/120338442/224820575-19d5080d-cb5d-4318-bbfb-2b778d842a39.MOV

**Device:**
 - Device: iPhone 13 Pro & iPad Air M1
 - OS: 16.3.1 (20D67)
 - Version: 1.2 Build 128

**Comment by sdubinsky** [comment]
Nice catch - we'll fix this right away.

**Comment by bvon** [comment]
Issue seems resolved in Mammoth 2.
