### ISSUE TITLE
Please (re)consider placing the repost/boost information at the top of the message instead of the bottom.

### ISSUE THREAD

**Issue by dchansen42** [TheBLVD/mammoth#64]
**Is your feature request related to a problem? Please describe.**
It is not really a problem, I just find it a lot more efficient if I can see that a post is actually a repost right away rather than having to wait until after I read it to find out that it was a repost. For posts you have not seen before it does not usually matter. It mainly becomes an issue when you follow accounts which tend to re-post themselves such as some of the journalist/news accounts that I follow. With the repost information at the top then I can know right away if I see account-I-follow reposting themselves that I can  just scroll right past it because I have already read it. With the repost information at the bottom I am usually part way through the post before I realize that I may have read this already and then have to scroll down further to see if that is the case. It just takes significantly longer to get through my feed this way. 

**Describe the solution you'd like**
If it aligns with your design choices, I would like it if the repost information would be moved to the top of the post instead of at the bottom.

**Describe alternatives you've considered**
If this is asking for how it behaves in other clients then I can confirm that it is in Ice Cubes, Tooot, Mastodon and Metatext.

**Additional context**

**Comment by echidistanti** [comment]
Would be a good option to add

**Comment by tclementdev** [comment]
I agree. I would also like to have more options:

- remove the little squared user icon, which I find distracting and not really useful
- reduce the font size to make it less distracting

**Comment by bvon** [comment]
Reposts are now labeled above the boosted message!
