### ISSUE TITLE
"View in AR" for profile avatar loads profile header instead.

### ISSUE THREAD

**Issue by dchansen42** [TheBLVD/mammoth#65]
**Describe the bug**
When you long press on someone's profile avatar and select "View in AR" it loads the profile header instead. I am not certain if this is intended or not.

**To Reproduce**
1. Go to 'a profile (yours or someone else's)' that has a profile header. If you select a profile which does not have a header, such as mine, then there will not be anything to place in AR mode.
2. Long press on 'the avatar picture'
3. Scroll down to 'View in AR'. At this point the app is displaying the profile avatar as if that is what is going to be displayed.
4. Tap to place and you will see the profile header placed instead.

**Expected behavior**
Since it is the profile avatar that is being selected I would expect that the avatar is what is being placed in AR.

**Screenshots**
I can add a screenshot if needed.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 16.3.1
 - Version [e.g. 22]: 1.2 build 128

**Additional context**
When long pressing the profile header, it displays and properly places the profile header. I do not know if this was present in the 1.1/build 119 version.

**Comment by sdubinsky** [comment]
Sounds like a bug to me.  We'll look into it.
