### ISSUE TITLE
iPadOS App doesn't load likes or bookmarks in single-column mode when opening app

### ISSUE THREAD

**Issue by Maskross** [TheBLVD/mammoth#68]
**Describe the bug**
When launching the app if it's not open in the background already and if the app is setup in single-column mode, neither bookmarks nor likes are loaded when trying to access them with their respective buttons on the sidebar. Refreshing the timeline or switching accounts seems to fix the problem temporarily until the next time the app is opened after being cleared from memory.

**To Reproduce**
1. Make sure the app is not already open in the background
2. Launch the app
3. Press either the bookmarks or likes button

**Expected behavior**
To have bookmarks or likes load automatically, without having to go and manually refresh the timeline or switch accounts first.

**Screenshots**

![IMG_1483](https://user-images.githubusercontent.com/80612418/225809835-7b376bcb-c0a7-480e-9ae6-7a1cac5e1e5d.png)

![IMG_1482](https://user-images.githubusercontent.com/80612418/225809854-78be4aca-3fd2-4edb-9de6-f1f3f1c916e6.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11 (2021 - M1)
 - OS: iPadOS 16.3.1
 - Version [e.g. 22]: Version 1.2, Build 128

**Comment by NathanRLiu** [comment]
Nice find! I just submitted this issue to our internal issue tracker; will try & let you know when this gets fixed.
