### ISSUE TITLE
Accounts that have not set a username should be displayed with @ usertag

### ISSUE THREAD

**Issue by pjolt** [TheBLVD/mammoth#69]
When **Settings>Post Appearance>Display Name** is set to **Username** posts from accounts that have no username set will default to a blank empty line where username is supposed to show.

In these cases it would be great if Mammoth could recognize that username is not set and in those cases have a fallback to display the **Usertag @** instead. 

![B6EB71E1-10AC-496F-9925-FA532F027714](https://user-images.githubusercontent.com/120338442/226187559-13f9af8d-9ed9-49b3-aa5e-e4b7797cc587.jpeg)

**Comment by bdecrem** [comment]
Oh yes! I noticed this issue yesterday! Thanks - great fix

**Comment by bvon** [comment]
This has been fixed in Mammoth 2 :)
