### ISSUE TITLE
When using multiple timeline tabs, app doesn't remember which timeline is set to a tab and resets to Following on relaunch

### ISSUE THREAD

**Issue by pratul** [TheBLVD/mammoth#70]
**Describe the bug**

When using multiple timeline tabs, the app doesn't remember which timeline is set to a tab and resets to the Following timeline if the app is relaunched.

**To Reproduce**
1. Long press on one of the bottom bar buttons, that is not already a timeline
2. Tap on timeline, so now you have at least two timeline buttons 
3. Tap on the second timeline button to open it 
4. Tap on the dropdown in the top bar to select a different timeline instead of Following, for e.g. Community or Everything
5. Force quit the app and relaunch it, and you'll see that the second timeline has reset to Following

**Expected behavior**

The second timeline should remember which timeline I had selected. 

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 16.3.1
 - Version: 1.2 (128)

**Comment by bvon** [comment]
Issue resolved in Mammoth 2 (MAM-1899)
