### ISSUE TITLE
UI waste of space in toot detail view

### ISSUE THREAD

**Issue by echidistanti** [TheBLVD/mammoth#72]
In my opinion, the split display of the retweet and like counts into two separate lines is a waste of space. Instead, couldn't these numbers be displayed alongside the corresponding buttons in the top line?

**Screenshots**
![image](https://user-images.githubusercontent.com/5138294/227294978-380f1402-69e8-48da-a7b2-f07c5a113e64.jpeg)

**Smartphonr:**
 - Device: iPhone 14 pro
 - OS: iOS 16.3.1
 - Version 1.3

**Comment by bvon** [comment]
In version 2, this has been overhauled.
