### ISSUE TITLE
Add option for taptic feedback while scrolling the timeline

### ISSUE THREAD

**Issue by jocosejohn** [TheBLVD/mammoth#73]
I’ve come to love this feature in Ice Cubes. As each toot comes onto the screen while scrolling it does one little tap.

**Comment by NathanRLiu** [comment]
Great feedback! I think this would definitely help the app come to life — just submitted this as a feature request to our internal issue tracker.

**Comment by bvon** [comment]
Our engineers are currently working primarily on making sure that version 2 is as stable and reliable as possible. We currently have no plans to implement this at the moment unfortunately. Thank you for the suggestion!
