### ISSUE TITLE
GIF auto play in timeline

### ISSUE THREAD

**Issue by echidistanti** [TheBLVD/mammoth#75]
I would like to request the addition of a feature that allows for automatic GIF playback in my timeline. Currently, when I scroll through my feed, I have to manually click on each GIF to view it. This can be time-consuming and frustrating, especially if I'm trying to quickly catch up on my feed.

By adding the ability for GIFs to automatically play as I scroll, I can more easily and efficiently view the content in my timeline. This would greatly enhance my user experience and make using the Mammoth Mastodon client even more enjoyable.

I understand that some users may prefer to manually play each GIF, so I would appreciate it if this feature could be toggled on or off in the settings. This way, users who prefer the current behavior can continue to use Mammothin the way they're used to.

**Comment by NathanRLiu** [comment]
Earlier this week I was thinking this feature should be implemented but never got around to logging it and totally forgot about it! Thanks for submitting this issue, gonna submit this to the internal issue tracker and hopefully it should be addressed soon.

**Comment by bvon** [comment]
This has been added to Mammoth 2 (thankfully!)
