### ISSUE TITLE
Cleaner profil tab

### ISSUE THREAD

**Issue by xhaythemx** [TheBLVD/mammoth#78]
I feel that the profil tab take a lot of space and it’s not clean compared to ivory or ice cubes

**Comment by NathanRLiu** [comment]
Thanks for the feedback! Would you mind elaborating a little bit more on what you want to see changed? Would I be correct to assume that you think there's too much whitespace in the profile header?

**Comment by xhaythemx** [comment]
![697EFFF8-B44D-4865-970F-898874032EF7](https://user-images.githubusercontent.com/17109917/227744155-57a3f156-9a7f-44c3-b7f3-c7f1ec442be4.jpeg)


This an example

**Comment by NathanRLiu** [comment]
Okay got it! Very nice feedback, I agree that this page needs to be more efficient in terms of we're using the on-screen real estate. I just submitted this into our internal issue tracker, and from there the team will work to decide how we can condense the information into a more efficient display

**Comment by bvon** [comment]
Significant changes were made to the profile tab in Mammoth 2! :)
