### ISSUE TITLE
Lazy loading content while scrolling causes viewport shift

### ISSUE THREAD

**Issue by morganwdavis** [TheBLVD/mammoth#84]
**Describe the bug**
While scrolling upwards and reading increasingly newer feed entries, the lazy loading images and linked article preview insertions causes the scroll position to move as content is shifted down after the content appears. This requires constant re-scrolling around to find where you last left off.

**To Reproduce**
1. Go to Following feed column
2. Scroll upwards
3. Notice how the shifting of content loading changes the viewport and scroll position

**Expected behavior**
As images and link previews are loaded and rendered into the content flow, the current scroll position should be maintained by computing the corresponding height offset.

**Screenshots**
Not possible to demonstrate from screenshot

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: [e.g. iOS8.1] 16.4.1
 - Version [e.g. 22]: Most recent as of 4/10/2023
 
**Additional context**
N/a

**Comment by NathanRLiu** [comment]
Thanks for the feedback. I can see how this would be frustrating! Will file a ticket and have the team look into this

**Comment by dchansen42** [comment]
I can confirm that this happens on iPhones as well.

**Comment by bvon** [comment]
Posts with links, images, etc. are now loaded properly when fetching in Mammoth 2.
