### ISSUE TITLE
Can we please have the TestFlight back?

### ISSUE THREAD

**Issue by cherryswiftie13** [TheBLVD/mammoth#85]
It would be nice if we could have the TestFlight back for this app. I would love to be able to use it via TestFlight because the App Store has weird issues on my iPhone. It's much easier to use Mammoth through TestFlight. Can you start using TestFlight again? It would be really nice. You seem to release updates pretty often so maybe you could publish it through TestFlight a bit early, or if not for testing, just update it through TestFlight while the update is being reviewed on the App Store?

PLEASE??? 🥺🥺🥺

**Comment by NathanRLiu** [comment]
Hey there! We appreciate the feedback. Right now we're mostly focusing on helping more people discover & get started w/ Mastodon, which means that we want the bulk of our resources to be directed towards the App Store and it wouldn't be as ideal having our attention split between both App Store and Test Flight releases. I'll still let the team know and leave the issue open for consideration, but I think the tentative answer is probably going to be a no :(

**Comment by bvon** [comment]
TestFlight invites will be issued upon request providing we have openings :)

Closing issue!
