### ISSUE TITLE
Crash when viewing message tab

### ISSUE THREAD

**Issue by mikix** [TheBLVD/mammoth#87]
**Describe the bug**
I can reliably trigger a crash in Mammoth when trying to view the “message” tab, which is holding a deleted DM I sent to myself -- looks like Mammoth sees that deleted message and freaks out.

**To Reproduce**
- Send private DM to myself
- Delete that accidental message
- Now I’m in the buggy state where anytime I try to view the messages tab, Mammoth crashes

**Expected behavior**
No crash, viewing my messages minus the deleted one

**Smartphone (please complete the following information):**
 - iPhone 11
 - OS: iOS 16.4.1
 - Version 153

**Comment by NathanRLiu** [comment]
I tried following the steps to reproduce that you suggested and it was totally fine for me. I'm also on version 153. What instance was your account on when this issue occurred?

**Comment by NathanRLiu** [comment]
@mikix We'll add an official fix for the next update, but if you want the issue fixed now all you have to do is go into Settings > Clear Cache and Data > Messages.

**Comment by mikix** [comment]
Yup! Can confirmed that worked. Cheers and thank you!

**Comment by bdecrem** [comment]
yeay!
