### ISSUE TITLE
Consider showing verified links inline with rest of profile

### ISSUE THREAD

**Issue by mikix** [TheBLVD/mammoth#89]
**Is your feature request related to a problem? Please describe.**
When viewing a profile, it may not be obvious that they are who they say they are.

I know that the concept of verification is inherently muddier in the fediverse, but we do have at least one common tool — verified links.

**Describe the solution you'd like**
Verified links feel like (potentially) highly relevant facts that ought to be surfaced without special effort by the user and placed on the main profile page, along with the profile’s note/description.

(Currently, Mammoth hides all links behind an “Info and Links” button.)

I don’t feel as strongly about non-verified fields. Those might reasonably be considered “noise” that clutters the profile. Hell, so could verified links — this whole suggestion is subjective UX. But I’m shooting my shot anyway.

**Describe alternatives you've considered**
I’m not a UX person - there may be better ways of surfacing verified links. But I feel like they could be useful to prominently display in some fashion.

**Comment by NathanRLiu** [comment]
Interesting. We're currently working on a redesign of the profile page anyway, so I'll fwd this feedback along to the design team

**Comment by bvon** [comment]
Mammoth 2 now recognizes rel="me" link attributes in profiles for verifying accounts
