### ISSUE TITLE
OIDC sign into Mastodon fails

### ISSUE THREAD

**Issue by btobolaski** [TheBLVD/mammoth#90]
**Describe the bug**

when attempting to sign into a Mastodon instance with OIDC, I get sent to a page that simply says ‘Not found. Authentication passthru.’ instead of being redirected to the Auth provider. Not sure how to debug as it works properly when visiting the instance in a web browser.

**To Reproduce**

*Note:* You won’t be able to hit the Auth provider publicly but, you should get redirected to it.

1. Try to sign into out.ruin.io
2. Tap on the Authentik button
3. See error page

**Expected behavior**

Redirected to the Auth provider, complete the Auth workflow, get redirected back to the mastodon instance and then the sign in workflow in mammoth completes.

**Screenshots**

![Screenshot 2023-04-20 at 11 28 55 AM](https://user-images.githubusercontent.com/363694/233429777-5c75bb34-f175-4d43-9f09-d17349a77fff.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 16.4.1
 - Version: The current App Store version, can’t get to settings without signing into an instance and I can’t sign in.

**Comment by NathanRLiu** [comment]
Oh no! Sucks that you weren't able to sign in. I'll create a bug report ticket on our internal issue tracker so this can get looked into.

**Comment by bvon** [comment]
Closing this issue (see MAM-1458)
