### ISSUE TITLE
Cache of profiles don’t seem to get updated

### ISSUE THREAD

**Issue by mikix** [TheBLVD/mammoth#91]
**Describe the bug**
Profiles will sometimes appear as one (older) thing, then update shortly, as if I were viewing a cached version first. Which is fine.

But then viewing the profile a second time, it happens again. That feels unexpected.

I don’t know if the cache is server side or local, but either way…

**To Reproduce**

This I’m less sure on. For me, it was:
1. Open (and follow?) an account yesterday.
2. That account’s profile changes (in this case, description + locked status)
3. Click on their profile today.
4. See that your client first shows old, then new profile.
5. Go back.
6. Click profile again, and see same transition from old to new.

**Expected behavior**
That updated profile content would be saved in the same manner as the original cached content was and I’d only see the profile visually refresh once.

**Screenshots**
This is me opening a profile that gets quickly updated, twice.

https://user-images.githubusercontent.com/1196901/233840013-8f9f6fa9-bb6b-4075-83b8-efb5cc18ddc6.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.4.1
 - Version 153

**Comment by NathanRLiu** [comment]
Nice find! I'll log this in our issue tracker right away.

**Comment by bvon** [comment]
Issue has been resolved in Mammoth 2.
