### ISSUE TITLE
Media image view does not fit actual image size when using "Scale to Fit" option

### ISSUE THREAD

**Issue by tclementdev** [TheBLVD/mammoth#96]
This is best understood by looking at the attached screenshot. When using the Settings > Media > Scale to Fit options, the image view on screen does not fit the actual image size, potentially losing a lot of screen real estate.

To reproduce, enable the "Scale to Fit" options, then post images of different ratios.

![image_size](https://github.com/TheBLVD/mammoth/assets/1420909/fa783d3c-9de6-4eb7-b7f8-ebb52e0e8238)

**Comment by bdecrem** [comment]
Hi! Thanks for reporting this.  We are working on design improvements in the app, in particular around image galleries, cropping of images etc. Will let you know when we have progress on this!

**Comment by bvon** [comment]
Image previews and scaling have been fixed in version 2
