### ISSUE TITLE
Broken links in post

### ISSUE THREAD

**Issue by tclementdev** [TheBLVD/mammoth#97]
See attached screenshots from mammoth vs. web interface. Several links are broken, others not, I am not sure why.

Link to post shown in screenshots: https://mastodon.social/@mjtsai/110351485007268034

![mammoth](https://github.com/TheBLVD/mammoth/assets/1420909/7281af6a-34cd-45a7-8508-ce31b042d9f1)

<img width="369" alt="web" src="https://github.com/TheBLVD/mammoth/assets/1420909/1a91cd40-08c2-473a-9580-0a58f05ad2a7">

**Comment by tclementdev** [comment]
Another thing: maybe it would be best to not show a preview at all when there are more than one link.

**Comment by lutoma** [comment]
Similarly, links on this account get cut off in Mammoth, but work on web: https://ard.social/@tagesschau

**Comment by bvon** [comment]
Looks like this has been addressed in Mammoth 2 (MAM-2334)
