### ISSUE TITLE
Default cursor location when replying to a post is incorrect

### ISSUE THREAD

**Issue by gwcali** [TheBLVD/mammoth#98]
**Describe the bug**
When replying to a post, it places the cursor before the username, so you need to move the cursor to the right of the username to start typing.

**To Reproduce**
1. Reply to post
2. The cursor is placed before (to the left) of the username

**Expected behavior**
The cursor should be placed after (to the right) of the username, or below the username, so I can just start typing my message.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.5
 - Version 1.6: 175

**Additional context**
Makes Mammoth very cumbersome to reply to posts.

**Comment by bdecrem** [comment]
Hi there! Thanks for reporting this. Are you in Mammoth 1.6? I am unable to reproduce this: for me it does exactly what you request, see attached video clip. I've tested in both a timeline and in a post details view. LMK what version / OS / device you're on and how I can reproduce...
https://github.com/TheBLVD/mammoth/assets/3072/e6397d37-b90e-43bd-845b-c99fdbc59a5c

**Comment by gwcali** [comment]
My device, version and OS are in the original ticket - iPhone 14 Pro, iOS 16.5 and Mammoth v1.6 build 175.
Screen recordings attached. It was constant last night but today it seems to randomly happen, not all the time. There are also times where it does not populate the username at all when replying.

https://github.com/TheBLVD/mammoth/assets/7017846/7ee500f9-bf36-4606-a8ea-22acdaafc7ee
https://github.com/TheBLVD/mammoth/assets/7017846/dfeb3509-b5bd-44b0-b42a-be14071ea60c

**Comment by bdecrem** [comment]
oh man, that's annoying! sorry you're getting that. filing a ticket now. fair warning: sprints 7 and 8 are 90% feature releases, so it may take us a few weeks to get to this

**Comment by bvon** [comment]
Not seeing this issue in Mammoth 2; unable to repro.
